In [1]:
import pandas as pd
import numpy as np
import math as mt
import os

In [2]:
csv = pd.read_csv('../datas/2016..',encoding='iso-8859-1',delimiter='#')

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,12,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [7]:
csv = pd.read_csv('../datas/2013/201312_Servidores/20131231_Cadastro.csv',encoding='iso-8859-1',delimiter='\t')

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [28]:
csv.shape

(805747, 42)

In [9]:
csv.columns.values

array(['Id_SERVIDOR_PORTAL', 'NOME', 'CPF', 'MATRICULA', 'DESCRICAO_CARGO',
       'CLASSE_CARGO', 'REFERENCIA_CARGO', 'PADRAO_CARGO', 'NIVEL_CARGO',
       'SIGLA_FUNCAO', 'NIVEL_FUNCAO', 'FUNCAO', 'CODIGO_ATIVIDADE',
       'ATIVIDADE', 'OPCAO_PARCIAL', 'COD_UORG_LOTACAO', 'UORG_LOTACAO',
       'COD_ORG_LOTACAO', 'ORG_LOTACAO', 'COD_ORGSUP_LOTACAO',
       'ORGSUP_LOTACAO', 'COD_UORG_EXERCICIO', 'UORG_EXERCICIO',
       'COD_ORG_EXERCICIO', 'ORG_EXERCICIO', 'COD_ORGSUP_EXERCICIO',
       'ORGSUP_EXERCICIO', 'TIPO_VINCULO', 'SITUACAO_VINCULO',
       'DATA_INICIO_AFASTAMENTO', 'DATA_TERMINO_AFASTAMENTO',
       'REGIME_JURIDICO', 'JORNADA_DE_TRABALHO',
       'DATA_INGRESSO_CARGOFUNCAO', 'DATA_NOMEACAO_CARGOFUNCAO',
       'DATA_INGRESSO_ORGAO', 'DOCUMENTO_INGRESSO_SERVICOPUBLICO',
       'DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO',
       'DIPLOMA_INGRESSO_CARGOFUNCAO', 'DIPLOMA_INGRESSO_ORGAO',
       'DIPLOMA_INGRESSO_SERVICOPUBLICO', 'UF_EXERCICIO'], dtype=object)

In [4]:
csv[['Id_SERVIDOR_PORTAL', 'NOME', 'CPF', 'MATRICULA']].head(5)

Id_SERVIDOR_PORTAL                    NOME             CPF MATRICULA
0             1000000    PAULO MARTINS SOARES  ***.787.200-**   002****
1             1000000    PAULO MARTINS SOARES  ***.787.200-**   002****
2             1000001          ANALIA BATISTA  ***.600.796-**   006****
3             1000002     ARY DE NOROES FILHO  ***.124.863-**   005****
4             1000003  EDUARDO BRUNO OLIVEIRA  ***.243.821-**   015****

In [4]:
diplomas = []
lib_diplomas = {}

for v in csv['DIPLOMA_INGRESSO_SERVICOPUBLICO']:
    if v not in diplomas:
        diplomas.append(v)
        lib_diplomas[v] = 1
    else:
        lib_diplomas[v] += 1

print(diplomas)

['PORTARIA', 'CARTA', 'CONTRATO', 'INSTRUCAO NORMATIVA', nan, 'PROCESSO', 'MEMORANDO', 'LEI', 'OUTROS', 'BOLETIM INTERNO', 'ORDEM DE SERVICO', 'EXP. MOTIVOS', 'OFICIO', 'DECRETO-LEI', 'EDITAL', 'PAPELETA', 'ATO', 'DECISAO JUDICIAL', 'DECRETO', 'CERTIDAO', 'AVISO', 'REQUERIMENTO', 'DECRETO-LEGISLATIVO', 'TELEX', 'PARECER', 'APOSTILA', 'NORMA COMPLEMENTAR', 'DESPACHO', 'EMEND CONSTITUCIONAL', 'RESOLUCAO', 'LEI COMPLEMENTAR', 'CONSTITUICAO FEDERAL', 'DEC.ADMINIST. MARE', 'MEDIDA PROVISORIA', 'ATO DE CONCESSAO', 'RELATORIO', 'ATO DO CONGRESSO', 'FORMULARIO', 'ATA', 'TERMO DE OPCAO', 'AçãO CIVIL', 'OFICIO CIRCULAR', 'ATESTADO MEDICO', 'COMUNICA SIAPE']


In [77]:
atividade_funcao = csv.values[:,9:14]
categorias_atv_fnc = []

for c in range(len(atividade_funcao)):
    if pd.isnull(atividade_funcao[c][2]) == False and pd.isnull(atividade_funcao[c][4]):
        print(atividade_funcao[c][2], atividade_funcao[c][4])

CARGO DE  DIRECAO - CD - IFES nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIF

GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan


GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
DIRECAO E ASSESSORAMENTO SUPERIOR nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
DIRECAO E ASSESSORAMENTO SUPERIOR nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
DIRECAO E ASSESSORAMENTO SUPERIOR nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIFICACAO DE FUNCAO DE CONFIANCA nan
GRATIF

## Funções

In [67]:
len(categorias_atv_fnc)

50

In [69]:
categorias_atv_fnc

['FUNCAO GRATIFICADA - IFES',
 nan,
 'DIRECAO E ASSESSORAMENTO SUPERIOR',
 'FUNCAO GRATIFICADA LEI 8.216/91',
 'FUNCAO GRATIFICADA QUADRO PERMANENTE',
 'CARGO DE  DIRECAO - CD - IFES',
 'FUNCAO COMISSIONADA DE COORD. CURSO',
 'FUNCAO COMISSIONADA TECNICA',
 'FUNCAO COMISSIONADA DO PODER EXECUTIVO',
 'GRAT SERV EXT/CENSO-96 - TEMPORARIA',
 'FCINSS - FUNCAO COMISSIONADA INSS',
 'FCDNIT - FUNC.COMISSIONADA DNIT',
 'CARGO COMISSIONADO DE DIRECAO',
 'CARGO COMISSIONADO DE ASSESSORIA',
 'GRATIFICACAO TEMPORARIA - SIPAM',
 'CARGO COMISSIONADO DE TECNICO',
 'GRATIF. REPRESENTACAO DE GABINETE (MIN)',
 'FUNCAO GRATIFICADA',
 'CARGO COMISSIONADO TEMPORARIO',
 'GRATIFICACAO DE FUNCAO DE CONFIANCA',
 'PLANO DE FUNCOES GRATIFICADAS',
 'CARGO COMISS. DE GERENCIA EXECUTIVA',
 'GRATIF. REPRES. DE GAB. - APOIO(PR/VPR)',
 'FUNCAO COMISSIONADA DO BANCO CENTRAL',
 'CARGO DE SUPERVISOR - CSU/APO',
 'FUNCAO COMISSIONADA DO DPRF - FCPRF',
 'GRATIFICACAO DE REPRESENTACAO',
 'GRATIFICACAO TEMPORARIA',
 'PLANO D

## Atividades

In [63]:
len(categorias_atv_fnc)

455

In [64]:
categorias_atv_fnc

['COORDENADOR',
 nan,
 'CHEFE DE SERVICO',
 'FUNCAO GRATIFICADA',
 'DIRETOR ADJUNTO',
 'CHEFE',
 'COORDENADOR DE GRADUACAO',
 'SUPERVISOR',
 'CHEFE DE SECAO',
 'FUNCAO COMISSIONADA TECNICA',
 'CHEFE DE SECAO NIVEL MEDIO',
 'CHEFE DE SETOR',
 'CHEFE DE DIVISÃO',
 'ASSISTENTE ESPECIAL',
 'ASSISTENTE',
 'ASSISTENTE III',
 'COORDENADOR DE POS-GRADUACAO',
 'CHEFE DE UNIDADE',
 'ASSISTENTE INTERMEDIARIO',
 'DIRETOR GERAL',
 'DIRETOR',
 'CHEFE DE DIVISAO',
 'COORDENADOR DE CURSO',
 'CHEFE DE AGENCIA',
 'SECRETARIO EXECUTIVO',
 'CHEFE DE CENTRO',
 'SECRETARIO',
 'SECRETARIA DE ORG.COLEGIADOS',
 'CHEFE DE NUCLEO',
 'COORDENADOR DE AREA',
 'CHEFE DE GABINETE',
 'GERENTE EXECUTIVO',
 'ASSIST. ADMINISTRATIVO',
 'SUBPROCURADOR',
 'AGENTE DA RECEITA FEDERAL',
 'ASSESSOR TECNICO',
 'ASSESSOR',
 'GRATIFICACAO TEMPORARIA-SIPAM',
 'COORDENADOR GERAL',
 'PRO-REITOR',
 'CHEFE DE EQUIPE',
 'GERENTE',
 'PRO-REITOR ADJUNTO',
 'AUXILIAR DE GABINETE',
 'ENCARREGADO SETOR/SUREG GF-IV',
 'CHEFE DE SERVICO FINANC

In [65]:
atividade_funcao

array([['FG', '0004', 'FUNCAO GRATIFICADA - IFES', '0033', 'COORDENADOR'],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       ..., 
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]], dtype=object)

In [22]:
#Verificar se todas as tuplas estão nulas
csv.DATA_NOMEACAO_CARGOFUNCAO.isnull().all()

True

In [24]:
davi = []
for d in csv.values:
    if d[1] == 'ANDREIA LIBORIO SAMPAIO':
        davi.append(d)

In [25]:
for d in range(len(davi[0])):
    print(str(davi[0][d]) +":"+str(csv.columns[d]))

1748166:Id_SERVIDOR_PORTAL
ANDREIA LIBORIO SAMPAIO:NOME
***.141.003-**:CPF
012****:MATRICULA
nan:DESCRICAO_CARGO
nan:CLASSE_CARGO
nan:REFERENCIA_CARGO
nan:PADRAO_CARGO
nan:NIVEL_CARGO
CD:SIGLA_FUNCAO
0004:NIVEL_FUNCAO
CARGO DE  DIRECAO - CD - IFES:FUNCAO
2049:CODIGO_ATIVIDADE
COORDENADOR DE COORDENADORIA:ATIVIDADE
Sim:OPCAO_PARCIAL
26233000000516.0:COD_UORG_LOTACAO
CAMPUS DA UFC EM QUIXADA/DIRETORIA:UORG_LOTACAO
26233:COD_ORG_LOTACAO
UNIVERSIDADE FEDERAL DO CEARA:ORG_LOTACAO
15000:COD_ORGSUP_LOTACAO
MINISTERIO DA EDUCACAO:ORGSUP_LOTACAO
26233000001395.0:COD_UORG_EXERCICIO
COORD DE PROGRAMAS ACADEMICOS/CUQUIXADA:UORG_EXERCICIO
26233:COD_ORG_EXERCICIO
UNIVERSIDADE FEDERAL DO CEARA:ORG_EXERCICIO
15000:COD_ORGSUP_EXERCICIO
MINISTERIO DA EDUCACAO:ORGSUP_EXERCICIO
1:TIPO_VINCULO
ATIVO PERMANENTE:SITUACAO_VINCULO
Não informada:DATA_INICIO_AFASTAMENTO
Não informada:DATA_TERMINO_AFASTAMENTO
REGIME JURIDICO UNICO:REGIME_JURIDICO
DEDICACAO EXCLUSIVA:JORNADA_DE_TRABALHO
10/06/2016:DATA_INGRESSO_CA

In [20]:
pd.DataFrame(davi[0], columns=csv.columns)

ValueError: Shape of passed values is (1, 42), indices imply (42, 42)

In [34]:
davi = []
for d in csv.values:
    if d[1] == 'ANDRE WESLEY BARBOSA RODRIGUES':
        davi.append(d)

In [35]:
for d in range(len(davi[0])):
    print(str(davi[0][d]) +":"+str(csv.columns[d]))

1580148:Id_SERVIDOR_PORTAL
ANDRE WESLEY BARBOSA RODRIGUES:NOME
***.812.254-**:CPF
017****:MATRICULA
nan:DESCRICAO_CARGO
nan:CLASSE_CARGO
nan:REFERENCIA_CARGO
nan:PADRAO_CARGO
nan:NIVEL_CARGO
CD:SIGLA_FUNCAO
0004:NIVEL_FUNCAO
CARGO DE  DIRECAO - CD - IFES:FUNCAO
3121:CODIGO_ATIVIDADE
VICE DIRETOR:ATIVIDADE
Sim:OPCAO_PARCIAL
26233000000499.0:COD_UORG_LOTACAO
CAMPUS DA UFC NO CARIRI/DIRETORIA:UORG_LOTACAO
26233:COD_ORG_LOTACAO
UNIVERSIDADE FEDERAL DO CEARA:ORG_LOTACAO
15000:COD_ORGSUP_LOTACAO
MINISTERIO DA EDUCACAO:ORGSUP_LOTACAO
26233000001104.0:COD_UORG_EXERCICIO
DIRETORIA DO C DE CIENC E TECNOLOGIA:UORG_EXERCICIO
26233:COD_ORG_EXERCICIO
UNIVERSIDADE FEDERAL DO CEARA:ORG_EXERCICIO
15000:COD_ORGSUP_EXERCICIO
MINISTERIO DA EDUCACAO:ORGSUP_EXERCICIO
1:TIPO_VINCULO
ATIVO PERMANENTE:SITUACAO_VINCULO
Não informada:DATA_INICIO_AFASTAMENTO
Não informada:DATA_TERMINO_AFASTAMENTO
REGIME JURIDICO UNICO:REGIME_JURIDICO
DEDICACAO EXCLUSIVA:JORNADA_DE_TRABALHO
03/07/2014:DATA_INGRESSO_CARGOFUNCAO
nan

In [31]:
for d in range(len(davi[0])):
    print(str(davi[0][d]) +":"+str(csv.columns[d]))

1305112:Id_SERVIDOR_PORTAL
ALINY ABREU DE SOUSA MONTEIRO:NOME
***.441.343-**:CPF
037****:MATRICULA
nan:DESCRICAO_CARGO
nan:CLASSE_CARGO
nan:REFERENCIA_CARGO
nan:PADRAO_CARGO
nan:NIVEL_CARGO
CD:SIGLA_FUNCAO
0004:NIVEL_FUNCAO
CARGO DE  DIRECAO - CD - IFES:FUNCAO
2049:CODIGO_ATIVIDADE
COORDENADOR DE COORDENADORIA:ATIVIDADE
Sim:OPCAO_PARCIAL
26233000000946.0:COD_UORG_LOTACAO
CAMPUS DA UFC DE RUSSAS:UORG_LOTACAO
26233:COD_ORG_LOTACAO
UNIVERSIDADE FEDERAL DO CEARA:ORG_LOTACAO
15000:COD_ORGSUP_LOTACAO
MINISTERIO DA EDUCACAO:ORGSUP_LOTACAO
26233000001397.0:COD_UORG_EXERCICIO
COORD DE PROGRAMAS ACADEMICOS/CRUSSAS:UORG_EXERCICIO
26233:COD_ORG_EXERCICIO
UNIVERSIDADE FEDERAL DO CEARA:ORG_EXERCICIO
15000:COD_ORGSUP_EXERCICIO
MINISTERIO DA EDUCACAO:ORGSUP_EXERCICIO
1:TIPO_VINCULO
ATIVO PERMANENTE:SITUACAO_VINCULO
Não informada:DATA_INICIO_AFASTAMENTO
Não informada:DATA_TERMINO_AFASTAMENTO
REGIME JURIDICO UNICO:REGIME_JURIDICO
DEDICACAO EXCLUSIVA:JORNADA_DE_TRABALHO
10/06/2016:DATA_INGRESSO_CARGOFUNC

In [27]:
for d in range(len(davi[0])):
    print(str(davi[0][d]) +":"+str(csv.columns[d]))

1699401:Id_SERVIDOR_PORTAL
ANTONIO NELSON LIMA DA COSTA:NOME
***.118.753-**:CPF
015****:MATRICULA
nan:DESCRICAO_CARGO
nan:CLASSE_CARGO
nan:REFERENCIA_CARGO
nan:PADRAO_CARGO
nan:NIVEL_CARGO
CD:SIGLA_FUNCAO
0004:NIVEL_FUNCAO
CARGO DE  DIRECAO - CD - IFES:FUNCAO
3121:CODIGO_ATIVIDADE
VICE DIRETOR:ATIVIDADE
Sim:OPCAO_PARCIAL
26233000000964.0:COD_UORG_LOTACAO
UNIVERSIDADE FEDERAL DO CARIRI:UORG_LOTACAO
26233:COD_ORG_LOTACAO
UNIVERSIDADE FEDERAL DO CEARA:ORG_LOTACAO
15000:COD_ORGSUP_LOTACAO
MINISTERIO DA EDUCACAO:ORGSUP_LOTACAO
26233000001103.0:COD_UORG_EXERCICIO
DIR DO CENTRO DE CIENC AGR E DA BIODIV:UORG_EXERCICIO
26233:COD_ORG_EXERCICIO
UNIVERSIDADE FEDERAL DO CEARA:ORG_EXERCICIO
15000:COD_ORGSUP_EXERCICIO
MINISTERIO DA EDUCACAO:ORGSUP_EXERCICIO
1:TIPO_VINCULO
ATIVO PERMANENTE:SITUACAO_VINCULO
Não informada:DATA_INICIO_AFASTAMENTO
Não informada:DATA_TERMINO_AFASTAMENTO
REGIME JURIDICO UNICO:REGIME_JURIDICO
DEDICACAO EXCLUSIVA:JORNADA_DE_TRABALHO
03/07/2014:DATA_INGRESSO_CARGOFUNCAO
nan:DA

In [23]:
for d in range(len(davi[0])):
    print(str(davi[0][d]) +":"+str(csv.columns[d]))

1473735:Id_SERVIDOR_PORTAL
DAVI ROMERO DE VASCONCELOS:NOME
***.931.793-**:CPF
015****:MATRICULA
nan:DESCRICAO_CARGO
nan:CLASSE_CARGO
nan:REFERENCIA_CARGO
nan:PADRAO_CARGO
nan:NIVEL_CARGO
CD:SIGLA_FUNCAO
0003:NIVEL_FUNCAO
CARGO DE  DIRECAO - CD - IFES:FUNCAO
0099:CODIGO_ATIVIDADE
DIRETOR:ATIVIDADE
Sim:OPCAO_PARCIAL
26233000000516.0:COD_UORG_LOTACAO
CAMPUS DA UFC EM QUIXADA/DIRETORIA:UORG_LOTACAO
26233:COD_ORG_LOTACAO
UNIVERSIDADE FEDERAL DO CEARA:ORG_LOTACAO
15000:COD_ORGSUP_LOTACAO
MINISTERIO DA EDUCACAO:ORGSUP_LOTACAO
26233000000516.0:COD_UORG_EXERCICIO
CAMPUS DA UFC EM QUIXADA/DIRETORIA:UORG_EXERCICIO
26233:COD_ORG_EXERCICIO
UNIVERSIDADE FEDERAL DO CEARA:ORG_EXERCICIO
15000:COD_ORGSUP_EXERCICIO
MINISTERIO DA EDUCACAO:ORGSUP_EXERCICIO
1:TIPO_VINCULO
ATIVO PERMANENTE:SITUACAO_VINCULO
Não informada:DATA_INICIO_AFASTAMENTO
Não informada:DATA_TERMINO_AFASTAMENTO
REGIME JURIDICO UNICO:REGIME_JURIDICO
DEDICACAO EXCLUSIVA:JORNADA_DE_TRABALHO
20/10/2015:DATA_INGRESSO_CARGOFUNCAO
nan:DATA_NOME

In [18]:
csv.head()

Id_SERVIDOR_PORTAL                    NOME             CPF MATRICULA  \
0             1000000    PAULO MARTINS SOARES  ***.787.200-**   002****   
1             1000000    PAULO MARTINS SOARES  ***.787.200-**   002****   
2             1000001          ANALIA BATISTA  ***.600.796-**   006****   
3             1000002     ARY DE NOROES FILHO  ***.124.863-**   005****   
4             1000003  EDUARDO BRUNO OLIVEIRA  ***.243.821-**   015****   

                      DESCRICAO_CARGO CLASSE_CARGO  REFERENCIA_CARGO  \
0                                 NaN          NaN               NaN   
1           TECNICO EM ARTES GRAFICAS            D               NaN   
2  ASSISTENTE EM CIENCIA E TECNOLOGIA            R               NaN   
3             AGENTE DE SAUDE PUBLICA            S               NaN   
4                          ANALISTA-A            A               NaN   

  PADRAO_CARGO  NIVEL_CARGO SIGLA_FUNCAO      ...      JORNADA_DE_TRABALHO  \
0          NaN          NaN           FG      ...        40 HORAS SEMANAIS   
1          414          NaN          NaN      ...        40 HORAS SEMANAIS   
2          III          NaN          NaN      ...        40 HORAS SEMANAIS   
3          III          NaN          NaN      ...        40 HORAS SEMANAIS   
4          NaN          6.0          NaN      ...        40 HORAS SEMANAIS   

  DATA_INGRESSO_CARGOFUNCAO DATA_NOMEACAO_CARGOFUNCAO DATA_INGRESSO_ORGAO  \
0                01/05/2016                       NaN          29/12/2008   
1                01/03/2005                       NaN          29/12/2008   
2                30/06/2000                       NaN          20/08/1979   
3                01/03/2006                       NaN          29/06/2010   
4                01/07/2015                       NaN          03/04/2007   

  DOCUMENTO_INGRESSO_SERVICOPUBLICO  DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO  \
0                         000046/92                            22/01/1992   
1                         000046/92                            22/01/1992   
2                         000000001                            20/08/1979   
3                         000000324                            01/06/1983   
4                                SN                            03/04/2007   

  DIPLOMA_INGRESSO_CARGOFUNCAO  DIPLOMA_INGRESSO_ORGAO  \
0                          NaN                     LEI   
1                          NaN                     LEI   
2                          NaN                PORTARIA   
3                          NaN                PORTARIA   
4                          NaN                   CARTA   

  DIPLOMA_INGRESSO_SERVICOPUBLICO  UF_EXERCICIO  
0                        PORTARIA            RS  
1                        PORTARIA           NaN  
2                        PORTARIA            MG  
3                        PORTARIA           NaN  
4                           CARTA            DF  

[5 rows x 42 columns]

### Qual a semantica entre:
* DATA_INGRESSO_CARGOFUNCAO; 
* DATA_NOMEACAO_CARGOFUNCAO; 
* DATA_INGRESSO_ORGAO; 
* DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO;

### Hipótese:
DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO => DATA_INGRESSO_ORGAO => DATA_INGRESSO_CARGOFUNCAO
DATA_NOMEACAO_CARGOFUNCAO é inexistente.

Mapeamento no Portal da Tranparência
* DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO => Ingresso no Serviço Público.Data de publicação
* DATA_INGRESSO_ORGAO => Data da última alteração no Órgão
* DATA_INGRESSO_CARGOFUNCAO => Data da Última Alteração no Cargo/Data da Última Alteração na Função


In [4]:
csv.head()

Id_SERVIDOR_PORTAL                    NOME             CPF MATRICULA  \
0             1000000    PAULO MARTINS SOARES  ***.787.200-**   002****   
1             1000000    PAULO MARTINS SOARES  ***.787.200-**   002****   
2             1000001          ANALIA BATISTA  ***.600.796-**   006****   
3             1000002     ARY DE NOROES FILHO  ***.124.863-**   005****   
4             1000003  EDUARDO BRUNO OLIVEIRA  ***.243.821-**   015****   

                      DESCRICAO_CARGO CLASSE_CARGO  REFERENCIA_CARGO  \
0                                 NaN          NaN               NaN   
1           TECNICO EM ARTES GRAFICAS            D               NaN   
2  ASSISTENTE EM CIENCIA E TECNOLOGIA            R               NaN   
3             AGENTE DE SAUDE PUBLICA            S               NaN   
4                          ANALISTA-A            A               NaN   

  PADRAO_CARGO  NIVEL_CARGO SIGLA_FUNCAO      ...      JORNADA_DE_TRABALHO  \
0          NaN          NaN           FG      ...        40 HORAS SEMANAIS   
1          414          NaN          NaN      ...        40 HORAS SEMANAIS   
2          III          NaN          NaN      ...        40 HORAS SEMANAIS   
3          III          NaN          NaN      ...        40 HORAS SEMANAIS   
4          NaN          6.0          NaN      ...        40 HORAS SEMANAIS   

  DATA_INGRESSO_CARGOFUNCAO DATA_NOMEACAO_CARGOFUNCAO DATA_INGRESSO_ORGAO  \
0                01/05/2016                       NaN          29/12/2008   
1                01/03/2005                       NaN          29/12/2008   
2                30/06/2000                       NaN          20/08/1979   
3                01/03/2006                       NaN          29/06/2010   
4                01/07/2015                       NaN          03/04/2007   

  DOCUMENTO_INGRESSO_SERVICOPUBLICO  DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO  \
0                         000046/92                            22/01/1992   
1                         000046/92                            22/01/1992   
2                         000000001                            20/08/1979   
3                         000000324                            01/06/1983   
4                                SN                            03/04/2007   

  DIPLOMA_INGRESSO_CARGOFUNCAO  DIPLOMA_INGRESSO_ORGAO  \
0                          NaN                     LEI   
1                          NaN                     LEI   
2                          NaN                PORTARIA   
3                          NaN                PORTARIA   
4                          NaN                   CARTA   

  DIPLOMA_INGRESSO_SERVICOPUBLICO  UF_EXERCICIO  
0                        PORTARIA            RS  
1                        PORTARIA           NaN  
2                        PORTARIA            MG  
3                        PORTARIA           NaN  
4                           CARTA            DF  

[5 rows x 42 columns]

## Chave primária de Cargo

In [57]:
import os

In [21]:
attr_cargos = []

In [22]:
for c in csv.columns.values:
    if 'CARGO' in c:
        attr_cargos.append(c)

In [23]:
attr_cargos

['DESCRICAO_CARGO',
 'CLASSE_CARGO',
 'REFERENCIA_CARGO',
 'PADRAO_CARGO',
 'NIVEL_CARGO',
 'DATA_INGRESSO_CARGOFUNCAO',
 'DATA_NOMEACAO_CARGOFUNCAO',
 'DIPLOMA_INGRESSO_CARGOFUNCAO']

In [24]:
csv.head(5)

Id_SERVIDOR_PORTAL                    NOME             CPF MATRICULA  \
0             1000000    PAULO MARTINS SOARES  ***.787.200-**   002****   
1             1000000    PAULO MARTINS SOARES  ***.787.200-**   002****   
2             1000001          ANALIA BATISTA  ***.600.796-**   006****   
3             1000002     ARY DE NOROES FILHO  ***.124.863-**   005****   
4             1000003  EDUARDO BRUNO OLIVEIRA  ***.243.821-**   015****   

                      DESCRICAO_CARGO CLASSE_CARGO  REFERENCIA_CARGO  \
0                                 NaN          NaN               NaN   
1           TECNICO EM ARTES GRAFICAS            D               NaN   
2  ASSISTENTE EM CIENCIA E TECNOLOGIA            R               NaN   
3             AGENTE DE SAUDE PUBLICA            S               NaN   
4                          ANALISTA-A            A               NaN   

  PADRAO_CARGO  NIVEL_CARGO SIGLA_FUNCAO      ...      JORNADA_DE_TRABALHO  \
0          NaN          NaN           FG      ...        40 HORAS SEMANAIS   
1          414          NaN          NaN      ...        40 HORAS SEMANAIS   
2          III          NaN          NaN      ...        40 HORAS SEMANAIS   
3          III          NaN          NaN      ...        40 HORAS SEMANAIS   
4          NaN          6.0          NaN      ...        40 HORAS SEMANAIS   

  DATA_INGRESSO_CARGOFUNCAO DATA_NOMEACAO_CARGOFUNCAO DATA_INGRESSO_ORGAO  \
0                01/05/2016                       NaN          29/12/2008   
1                01/03/2005                       NaN          29/12/2008   
2                30/06/2000                       NaN          20/08/1979   
3                01/03/2006                       NaN          29/06/2010   
4                01/07/2015                       NaN          03/04/2007   

  DOCUMENTO_INGRESSO_SERVICOPUBLICO  DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO  \
0                         000046/92                            22/01/1992   
1                         000046/92                            22/01/1992   
2                         000000001                            20/08/1979   
3                         000000324                            01/06/1983   
4                                SN                            03/04/2007   

  DIPLOMA_INGRESSO_CARGOFUNCAO  DIPLOMA_INGRESSO_ORGAO  \
0                          NaN                     LEI   
1                          NaN                     LEI   
2                          NaN                PORTARIA   
3                          NaN                PORTARIA   
4                          NaN                   CARTA   

  DIPLOMA_INGRESSO_SERVICOPUBLICO  UF_EXERCICIO  
0                        PORTARIA            RS  
1                        PORTARIA           NaN  
2                        PORTARIA            MG  
3                        PORTARIA           NaN  
4                           CARTA            DF  

[5 rows x 42 columns]

In [62]:
for d in os.listdir('../datas/2017/'):
    for c in os.listdir('../datas/2017/'+d):
        if 'Cadastro' in c:
            crg = pd.read_csv('../datas/2017/'+d+'/'+c,encoding='iso-8859-1',delimiter='\t')
            print(crg.REFERENCIA_CARGO.isnull().all())

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,12,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


True
True


In [68]:
#csv.REFERENCIA_CARGO.isnull().all() #Descarta REFERENCIA_CARGO -> Dado inexistente
#len(csv.CLASSE_CARGO.value_counts()) # Descarta CLASSE_CARGO #34
#len(csv.PADRAO_CARGO.value_counts()) #221
#len(csv.NIVEL_CARGO.value_counts()) #180
#len(csv.DESCRICAO_CARGO.value_counts()) #2255

34

In [46]:
cargos = []
for cargo in csv.DESCRICAO_CARGO.values:
    if cargo not in cargos:
        cargos.append(cargo)

cargos.remove(cargos[0])
len(cargos)

In [92]:
list(filter(lambda c: 'ANALISTA' in c, cargos))

['ANALISTA-A',
 'ANALISTA DE PESQUISA ENERGETICA',
 'ANALISTA ADMINISTRATIVO',
 'ANALISTA EM GEOCIENCIA',
 'ANALISTA CVM',
 'ANALISTA DE TECNOL DA INFORMACAO - 40H',
 'ANALISTA DO SEGURO SOCIAL',
 'ANALISTA TRIBUTARIO REC FEDERAL BRASIL',
 'ANALISTA DE GESTAO EM SAUDE',
 'ANALISTA DO BANCO CENTRAL',
 'ANALISTA AMBIENTAL',
 'ANALISTA',
 'ANALISTA EM INFRA-ESTRUT DE TRANSPORTES',
 'ANALISTA DE SISTEMA',
 'ANALISTA DE COMERCIO EXTERIOR',
 'ANALISTA TECNICO ADMINISTRATIVO III',
 'ANALISTA EM DESENVOLVIMENTO REGIONAL',
 'ANALISTA REFORMA DESENV AGRARIO',
 'ANALISTA DE INFRA-ESTRUTURA',
 'ANALISTA EM CIENCIA E TECNOLOGIA',
 'ANALISTA - ANALISTA DE PLANEJAMENTO',
 'ANALISTA-B',
 'ANALISTA TECNICO DE POLITICAS SOCIAIS',
 'ANALISTA DE TEC DA INFORMACAO',
 'ANALISTA - ANALISTA DE CONTABILIDADE',
 'ANALISTA DE PLANEJAMENTO E ORCAMENTO',
 'ANALISTA EM TECNOLOGIA DA INFORMACAO',
 'ANALISTA - ENGENHEIRO AGRONOMO-AGRICOLA',
 'ANALISTA TECNICO ADMINISTRATIVO',
 'ANALISTA TECNICO SUSEP',
 'ANALISTA B',

In [87]:
for c in csv.values:
    if pd.isnull(c[4]) == False and 'MEDICO II' == c[4]:
        print(c)

[1992423 'PAULO RENATO FIGUEIREDO FERREIRA' '***.150.140-**' '012****'
 'MEDICO II' 'C' nan '008' nan nan nan nan nan nan nan 99013200033000.0
 'SERVICO RADIOLOGIA' 99013 'HOSPITAL DE CLINICAS DE PORTO ALEGRE' 15000
 'MINISTERIO DA EDUCACAO' 99013150000000.0
 'COORDENADORIA DE GESTAO DE PESSOAS' '99013'
 'HOSPITAL DE CLINICAS DE PORTO ALEGRE' '15000' 'MINISTERIO DA EDUCACAO' 2
 'CELETISTA/EMPREGADO' 'Não informada' 'Não informada'
 'CONSOLIDACAO DAS LEIS DO TRABALHO' '36 HORAS SEMANAIS' '01/01/2012' nan
 '25/09/1998' nan 'Não informada' nan 'CONTRATO' nan 'RS']


In [88]:
all_cargos = []

In [89]:
#Todos os cargos de 2016
for d in os.listdir('../datas/2016/'):
    for c in os.listdir('../datas/2016/'+d):
        if 'Cadastro' in c:
            crg = pd.read_csv('../datas/2016/'+d+'/'+c,encoding='iso-8859-1',delimiter='\t')
            for cargo in crg.DESCRICAO_CARGO.values:
                if cargo not in all_cargos:
                    all_cargos.append(cargo)

#Todos os cargos de 2017
for d in os.listdir('../datas/2017/'):
    for c in os.listdir('../datas/2017/'+d):
        if 'Cadastro' in c:
            crg = pd.read_csv('../datas/2017/'+d+'/'+c,encoding='iso-8859-1',delimiter='\t')
            for cargo in crg.DESCRICAO_CARGO.values:
                if cargo not in all_cargos:
                    all_cargos.append(cargo)

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,12,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [91]:
len(all_cargos) #União de Todos os cargos de 2016 e 2017

2337

In [10]:
persol = []
for d in csv.values:
    if d[1] == 'ABIGAIL ANDRADE FERREIRA':
        print(d)

[2076644 'ABIGAIL ANDRADE FERREIRA' '***.064.091-**' '011****'
 'ASSISTENTE DE CHANCELARIA' 'S' nan 'V' nan nan nan nan nan nan nan
 35000000000332.0 'DIVISAO DE INFORMATICA' 35000
 'MINISTERIO DAS RELACOES EXTERIORES' 35000
 'MINISTERIO DAS RELACOES EXTERIORES' 35000000000332.0
 'DIVISAO DE INFORMATICA' 35000 'MINISTERIO DAS RELACOES EXTERIORES' 35000
 'MINISTERIO DAS RELACOES EXTERIORES' 2 'ATIVO PERMANENTE' 'Não informada'
 'Não informada' 'REGIME JURIDICO UNICO' '40 HORAS SEMANAIS' '01/07/2008'
 nan '20/02/1979' '000000024' '20/02/1979' nan 'PORTARIA' 'PORTARIA' nan]


In [13]:
csv.head(50)

ANO  MES  ID_SERVIDOR_PORTAL             CPF  \
0   2017    1             1000000  ***.787.200-**   
1   2017    1             1000001  ***.600.796-**   
2   2017    1             1000002  ***.124.863-**   
3   2017    1             1000004  ***.122.446-**   
4   2017    1             1000005  ***.761.819-**   
5   2017    1             1000010  ***.956.267-**   
6   2017    1             1000011  ***.519.384-**   
7   2017    1             1000012  ***.326.633-**   
8   2017    1             1000015  ***.812.017-**   
9   2017    1             1000016  ***.834.277-**   
10  2017    1             1000018  ***.497.603-**   
11  2017    1             1000020  ***.700.727-**   
12  2017    1             1000021  ***.745.709-**   
13  2017    1             1000023  ***.979.191-**   
14  2017    1             1000029  ***.824.921-**   
15  2017    1             1000030  ***.576.157-**   
16  2017    1             1000032  ***.397.336-**   
17  2017    1             1000033  ***.138.771-**   
18  2017    1             1000034  ***.934.353-**   
19  2017    1             1000035  ***.634.648-**   
20  2017    1             1000040  ***.865.526-**   
21  2017    1             1000041  ***.274.536-**   
22  2017    1             1000043  ***.964.281-**   
23  2017    1             1000045  ***.149.107-**   
24  2017    1             1000047  ***.839.307-**   
25  2017    1             1000049  ***.574.181-**   
26  2017    1             1000050  ***.116.526-**   
27  2017    1             1000051  ***.133.697-**   
28  2017    1             1000052  ***.767.375-**   
29  2017    1             1000053  ***.590.741-**   
30  2017    1             1000056  ***.226.544-**   
31  2017    1             1000058  ***.487.314-**   
32  2017    1             1000059  ***.571.118-**   
33  2017    1             1000063  ***.162.407-**   
34  2017    1             1000065  ***.948.275-**   
35  2017    1             1000067  ***.480.711-**   
36  2017    1             1000069  ***.242.688-**   
37  2017    1             1000070  ***.203.443-**   
38  2017    1             1000071  ***.396.960-**   
39  2017    1             1000078  ***.268.027-**   
40  2017    1             1000079  ***.891.196-**   
41  2017    1             1000082  ***.343.757-**   
42  2017    1             1000083  ***.490.420-**   
43  2017    1             1000091  ***.446.967-**   
44  2017    1             1000092  ***.407.210-**   
45  2017    1             1000093  ***.075.866-**   
46  2017    1             1000095  ***.767.470-**   
47  2017    1             1000096  ***.102.468-**   
48  2017    1             1000097  ***.731.249-**   
49  2017    1             1000098  ***.720.916-**   

                                    NOME REMUNERAÇÃO BÁSICA BRUTA (R$)  \
0                   PAULO MARTINS SOARES                       7332,99   
1                         ANALIA BATISTA                       9607,00   
2                    ARY DE NOROES FILHO                       6313,85   
3           MOISES ALBERTO CALLE AGUIRRE                      12132,29   
4               LAURA JANAINA DIAS AMATO                      11308,31   
5      DANIELLE CHAVES GONCALVES TAVARES                       3432,24   
6        JOSE EDSON CESAR DE ALBUQUERQUE                      17039,24   
7                 CINTIA FLORENCIO ALVES                      11916,65   
8                ANA CRISTINA PINTO REIS                      18891,58   
9           ELIANE PAVESI BARRETO SOARES                       9424,67   
10                LENA CAVALCANTE FALCAO                      13687,90   
11                       ADELMO GOLYNSKI                      15860,21   
12        MARIA AUREA DOS SANTOS RIBEIRO                       6211,50   
13                VALMI SILVA NASCIMENTO                       5659,49   
14             FERNANDO MORAIS RODRIGUES                      12132,29   
15          LEILA MARIA DOS SANTOS ALVES                       4340,76   
16               EDMILSON ALVES DA SILVA   

In [19]:
p = []
for d in csv.values:
    if float(d[5].replace(',','.')) > 0 and float(d[6].replace(',','.')) > 0:
        p.append(d)

In [21]:
p

[array([2017, 1, 1003600, '***.514.991-**',
        'ANTONIO JORGE RAMALHO DA ROCHA', '19704,94', '8006,54', '0,00',
        '0,00', '0,00', '0,00', '0,00', '0,00', '0,00', '0,00', '0,00',
        '0,00', '-3849,15', '-72,91', '-2167,54', '0,00', '0,00', '0,00',
        '0,00', '0,00', '0,00', '0,00', '13688,25', '7933,63', '458,00',
        '4144,80', '0,00', '0,00', '458,00', '4144,80', '0,00'], dtype=object),
 array([2017, 1, 1004378, '***.834.711-**', 'CLAUDIA FONSECA BUZZI',
        '31610,00', '1144,27', '0,00', '0,00', '0,00', '0,00', '0,00',
        '0,00', '0,00', '0,00', '2655,69', '0,00', '-7823,39', '0,00',
        '-2655,69', '-111,53', '0,00', '0,00', '0,00', '0,00', '0,00',
        '0,00', '23786,61', '1032,74', '458,00', '622,72', '0,00', '0,00',
        '458,00', '622,72', '0,00'], dtype=object),
 array([2017, 1, 1014116, '***.293.831-**',
        'ANA MARIA SENA RIBEIRO PASIANI', '13918,72', '1238,57', '0,00',
        '0,00', '1497,77', '0,00', '0,00', '0,00', '0,00',

## Total de Honorário dos Servidores

In [2]:
remuneracao = pd.read_csv('../datas/2016/201610_Servidores/20161031_Remuneracao.csv',encoding='iso-8859-1',delimiter='\t')
honorarios = pd.read_csv('../datas/2016/201610_Servidores/20161031_Honorarios(Jetons).csv',encoding='iso-8859-1',delimiter='\t')

In [6]:
observacoes = pd.read_csv('../datas/2016/201610_Servidores/20161031_Observacoes.csv',encoding='iso-8859-1',delimiter='\t')
cadastro = pd.read_csv('../datas/2016/201610_Servidores/20161031_Cadastro.csv',encoding='iso-8859-1',delimiter='\t')

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,12,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [263]:
remuneracao.head()

ANO  MES  ID_SERVIDOR_PORTAL             CPF  \
0  2016   10             1000000  ***.787.200-**   
1  2016   10             1000001  ***.600.796-**   
2  2016   10             1000002  ***.124.863-**   
3  2016   10             1000004  ***.122.446-**   
4  2016   10             1000005  ***.761.819-**   

                           NOME REMUNERAÇÃO BÁSICA BRUTA (R$)  \
0          PAULO MARTINS SOARES                       6779,03   
1                ANALIA BATISTA                       9151,22   
2           ARY DE NOROES FILHO                       6012,61   
3  MOISES ALBERTO CALLE AGUIRRE                      11554,56   
4      LAURA JANAINA DIAS AMATO                      10769,82   

  REMUNERAÇÃO BÁSICA BRUTA (U$) ABATE-TETO (R$) ABATE-TETO (U$)  \
0                          0,00            0,00            0,00   
1                          0,00            0,00            0,00   
2                          0,00            0,00            0,00   
3                          0,00            0,00            0,00   
4                          0,00            0,00            0,00   

  GRATIFICAÇÃO NATALINA (R$)             ...               \
0                       0,00             ...                
1                       0,00             ...                
2                       0,00             ...                
3                       0,00             ...                
4                       0,00             ...                

  DEMAIS DEDUÇÕES (U$) REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (R$)  \
0                 0,00                                     5380,94   
1                 0,00                                     7279,84   
2                 0,00                                     5592,39   
3                 0,00                                     8429,22   
4                 0,00                                     7754,39   

  REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (U$)  \
0                                        0,00   
1                                        0,00   
2                                        0,00   
3                                        0,00   
4                                        0,00   

  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (R$)(*)  \
0                                             801,24                         
1                                            1521,78                         
2                                             817,93                         
3                                             579,14                         
4                                            1100,00                         

  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (U$)(*)  \
0                                               0,00                         
1                                               0,00                         
2                                               0,00                         
3                                               0,00                         
4                                               0,00                         

  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (R$)(*)  \
0                                               0,00                           
1                                               0,00                           
2                                               0,00                           
3                                               0,00                           
4                                               0,00                           

  VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (U$)(*)  \
0                                               0,00                           
1                                               0,00                           
2                                               0,00                           
3                                               0,00                       

In [264]:
honorarios.head()

ANO  MES  ID_SERVIDOR_PORTAL             CPF  \
0  2016   10             1000885  ***.612.937-**   
1  2016   10             1003998  ***.641.298-**   
2  2016   10             1007140  ***.005.336-**   
3  2016   10             1008777  ***.059.377-**   
4  2016   10             1009387  ***.583.280-**   

                                   NOME  \
0      MAGDA MARIA DE REGINA CHAMBRIARD   
1                MARCUS VINICIUS SINVAL   
2  RODRIGO FONTENELLE DE ARAUJO MIRANDA   
3                          HO YIU CHENG   
4                   JANE FRAGA TUTIKIAN   

                                          EMPRESA    VALOR  
0            EMPRESA DE PESQUISA ENERGÉTICA - EPE  3248.21  
1        EMPRESA BRASIL DE COMUNICAÇÃO S.A. - EBC  1029.60  
2       INDÚSTRIAS NUCLEARES DO BRASIL S.A. - INB  3376.30  
3  EMPRESA DE PLANEJAMENTO E LOGÍSTICA S.A. - EPL  3171.38  
4     HOSPITAL DE CLÍNICAS DE PORTO ALEGRE - HCPA  3248.21

In [265]:
observacoes.head()

ANO  MES  ID_SERVIDOR_PORTAL             CPF  \
0  2016   10             1000018  ***.497.603-**   
1  2016   10             1000033  ***.138.771-**   
2  2016   10             1000053  ***.590.741-**   
3  2016   10             1000056  ***.226.544-**   
4  2016   10             1000067  ***.480.711-**   

                           NOME  \
0        LENA CAVALCANTE FALCAO   
1         MARISE SILVA SIQUEIRA   
2     ANGELICA ALVES DE AZEVEDO   
3  DAISY NUNES DE OLIVEIRA LIMA   
4    JOSE PEREIRA DA SILVA NETO   

                                          OBSERVACAO  
0  OS VALORES DEMONSTRADOS ACIMA INCLUEM REMUNERA...  
1  OS VALORES DEMONSTRADOS ACIMA INCLUEM REMUNERA...  
2                 SERVIDOR EM EXERCICIO NO EXTERIOR.  
3  OS VALORES DEMONSTRADOS ACIMA INCLUEM REMUNERA...  
4  OS VALORES DEMONSTRADOS ACIMA INCLUEM REMUNERA...

In [208]:
# Juntar todos os honorarios
servidor_honorario = {}

In [209]:
for h in honorarios.values:
    #ID_SERVIDOR_PORTAL
    if h[2] not in servidor_honorario:
        servidor_honorario[h[2]] = h[6]
    else:
        servidor_honorario[h[2]] += h[6]

In [210]:
for r in remuneracao.values:
    if r[2] in servidor_honorario:
        if float("{0:.2f}".format(round(servidor_honorario[r[2]],2))) != float("{0:.2f}".format(round(float(r[35].replace(',','.')),2))):
            print(str(r) + ' - '+ str(servidor_honorario[r[2]]))

[2016 1 1114862 '***.476.701-**' 'CARLOS AUGUSTO MOREIRA ARAUJO' '26523,92'
 '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '-5673,36' '0,00' '-2353,02' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '18497,54' '0,00' '765,70' '0,00' '0,00' '0,00' '765,70'
 '0,00' '6847,56'] - 3423.78
[2016 1 1199274 '***.055.601-**' 'MARCELO DE SIQUEIRA FREITAS' '29685,61'
 '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '-6613,03' '0,00' '-2476,86' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '20595,72' '0,00' '770,11' '0,00' '0,00' '0,00' '770,11'
 '0,00' '12191,79'] - 8051.68
[2016 1 1982053 '***.452.781-**' 'SERGIO CRUZ' '28132,10' '0,00' '0,00'
 '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '-6115,60'
 '0,00' '-2353,02' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '19663,48' '0,00' '761,98' '0,00' '0,00' '0,00' '761,98' '0,00' '7877,14'] - 3938.57


In [7]:
cadastro.head()

Id_SERVIDOR_PORTAL                    NOME             CPF MATRICULA  \
0             1000000    PAULO MARTINS SOARES  ***.787.200-**   002****   
1             1000000    PAULO MARTINS SOARES  ***.787.200-**   002****   
2             1000001          ANALIA BATISTA  ***.600.796-**   006****   
3             1000002     ARY DE NOROES FILHO  ***.124.863-**   005****   
4             1000003  EDUARDO BRUNO OLIVEIRA  ***.243.821-**   015****   

                      DESCRICAO_CARGO CLASSE_CARGO  REFERENCIA_CARGO  \
0                                 NaN          NaN               NaN   
1           TECNICO EM ARTES GRAFICAS            D               NaN   
2  ASSISTENTE EM CIENCIA E TECNOLOGIA            R               NaN   
3             AGENTE DE SAUDE PUBLICA            S               NaN   
4                          ANALISTA-A            A               NaN   

  PADRAO_CARGO  NIVEL_CARGO SIGLA_FUNCAO      ...      JORNADA_DE_TRABALHO  \
0          NaN          NaN           FG      ...        40 HORAS SEMANAIS   
1          414          NaN          NaN      ...        40 HORAS SEMANAIS   
2          III          NaN          NaN      ...        40 HORAS SEMANAIS   
3          III          NaN          NaN      ...        40 HORAS SEMANAIS   
4          NaN          6.0          NaN      ...        40 HORAS SEMANAIS   

  DATA_INGRESSO_CARGOFUNCAO DATA_NOMEACAO_CARGOFUNCAO DATA_INGRESSO_ORGAO  \
0                01/05/2016                       NaN          29/12/2008   
1                01/03/2005                       NaN          29/12/2008   
2                30/06/2000                       NaN          20/08/1979   
3                01/03/2006                       NaN          29/06/2010   
4                01/07/2015                       NaN          03/04/2007   

  DOCUMENTO_INGRESSO_SERVICOPUBLICO  DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO  \
0                         000046/92                            22/01/1992   
1                         000046/92                            22/01/1992   
2                         000000001                            20/08/1979   
3                         000000324                            01/06/1983   
4                                SN                            03/04/2007   

  DIPLOMA_INGRESSO_CARGOFUNCAO  DIPLOMA_INGRESSO_ORGAO  \
0                          NaN                     LEI   
1                          NaN                     LEI   
2                          NaN                PORTARIA   
3                          NaN                PORTARIA   
4                          NaN                   CARTA   

  DIPLOMA_INGRESSO_SERVICOPUBLICO  UF_EXERCICIO  
0                        PORTARIA            RS  
1                        PORTARIA           NaN  
2                        PORTARIA            MG  
3                        PORTARIA           NaN  
4                           CARTA            DF  

[5 rows x 42 columns]

In [8]:
for c in cadastro.values:
    if c[1] == 'CARLOS AUGUSTO MOREIRA ARAUJO':
        print(c)

[1114862 'CARLOS AUGUSTO MOREIRA ARAUJO' '***.476.701-**' '074****' nan nan
 nan nan nan 'DAS' '1014' 'DIRECAO E ASSESSORAMENTO SUPERIOR' '1025'
 'OUVIDORIA GERAL/OUVIDGR' 'Sim' nan nan 17000 'MINISTERIO DA FAZENDA'
 17000 'MINISTERIO DA FAZENDA' nan nan 17000 'MINISTERIO DA FAZENDA' 17000
 'MINISTERIO DA FAZENDA' 1 'ATIVO PERMANENTE' 'Não informada'
 'Não informada' 'REGIME JURIDICO UNICO' '40 HORAS SEMANAIS' '13/06/2007'
 nan '31/12/1996' '000000803' '31/12/1996' nan 'PORTARIA' 'PORTARIA' 'DF']
[1114862 'CARLOS AUGUSTO MOREIRA ARAUJO' '***.476.701-**' '074****'
 'AUDITOR FEDERAL DE FINANCAS E CONTROLE' 'S' nan 'IV' nan nan nan nan nan
 nan nan nan nan 17000 'MINISTERIO DA FAZENDA' 17000
 'MINISTERIO DA FAZENDA' nan nan 17000 'MINISTERIO DA FAZENDA' 17000
 'MINISTERIO DA FAZENDA' 2 'ATIVO PERMANENTE' 'Não informada'
 'Não informada' 'REGIME JURIDICO UNICO' '40 HORAS SEMANAIS' '30/06/2000'
 nan '31/12/1996' '000000803' '31/12/1996' nan 'PORTARIA' 'PORTARIA' nan]


In [266]:
for i in observacoes.values:
    if i[4] == 'MANOEL AUGUSTO CARDOSO DA FONSECA':
        print(i)

In [267]:
for i in honorarios.values:
    if i[4] == 'MANOEL AUGUSTO CARDOSO DA FONSECA':
        print(i)

[2016 10 1828300 '***.519.450-**' 'MANOEL AUGUSTO CARDOSO DA FONSECA'
 'CENTRO NACIONAL DE TECNOLOGIA ELETRÔNICA AVANÇADA S.A. - CEITEC' 3191.73]


In [268]:
s = None
for i in remuneracao.values:
    if i[4] == 'MANOEL AUGUSTO CARDOSO DA FONSECA':
        print(i)
        s = i 

[2016 10 1828300 '***.519.450-**' 'MANOEL AUGUSTO CARDOSO DA FONSECA'
 '22796,57' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '-5699,48' '0,00' '-1911,95' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '0,00' '15185,14' '0,00' '703,47' '0,00' '0,00' '0,00'
 '703,47' '0,00' '6383,46']


In [72]:
df = pd.DataFrame(s,remuneracao.columns.tolist())

### Casos estranhos

In [ ]:
#01/2016
#Caso 1
Total de honorários: 3423.78
    [2016 1 1114862 '***.476.701-**' 'CARLOS AUGUSTO MOREIRA ARAUJO'
 'BANCO DA AMAZÔNIA S.A. - BASA' 3423.78]
    
Tupla na remuneração: 6847,56
    [2016 1 1114862 '***.476.701-**' 'CARLOS AUGUSTO MOREIRA ARAUJO' '26523,92'
 '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '-5673,36' '0,00' '-2353,02' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '18497,54' '0,00' '765,70' '0,00' '0,00' '0,00' '765,70'
 '0,00' '6847,56']
Obs: Não possui registro no arquivo de observações
Portal da Tranparência: O valor do honorário está repetido (2 vezes), o que totaliza os 6847,56.
    
#Caso 2
Total de honorários:8051.68
    [2016 1 1199274 '***.055.601-**' 'MARCELO DE SIQUEIRA FREITAS'
 'EMPRESA DE TECNOLOGIA E INFORMAÇÕES DA PREVIDÊNCIA SOCIAL - DATAPREV'
 4140.11]
    [2016 1 1199274 '***.055.601-**' 'MARCELO DE SIQUEIRA FREITAS'
 'TELECOMUNICAÇÕES BRASILEIRAS S.A. - TELEBRAS' 3911.57]

Tupla na remuneração: 12191,79
    [2016 1 1199274 '***.055.601-**' 'MARCELO DE SIQUEIRA FREITAS' '29685,61'
 '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '-6613,03' '0,00' '-2476,86' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '20595,72' '0,00' '770,11' '0,00' '0,00' '0,00' '770,11'
 '0,00' '12191,79']
Obs: Ele possui observação (Observacoes.csv) referentes a remuneração
    [2016 1 1199274 '***.055.601-**' 'MARCELO DE SIQUEIRA FREITAS'
 'OS VALORES DEMONSTRADOS ACIMA INCLUEM REMUNERACOES PERCEBIDAS PELO SERVIDOR NO SEU ORGAO/EMPRESA DE ORIGEM']
Portal da Transparência: Recebeu duas vezes da DATAPREV e uma da TELEBRAS, totalizando 12191,79

#Caso 3
Total de honorários: 3938.57
    [2016 1 1982053 '***.452.781-**' 'SERGIO CRUZ'
 'EMPRESA BRASILEIRA DE INFRAESTRUTURA AEROPORTUÁRIA - INFRAERO' 3938.57]
    
Tupla na remuneração: 7877,14
    [2016 1 1982053 '***.452.781-**' 'SERGIO CRUZ' '28132,10' '0,00' '0,00'
 '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '-6115,60'
 '0,00' '-2353,02' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '19663,48' '0,00' '761,98' '0,00' '0,00' '0,00' '761,98' '0,00' '7877,14']
Obs: Ele possui observação (Observacoes.csv) referentes a remuneração
    [2016 1 1982053 '***.452.781-**' 'SERGIO CRUZ'
 'OS VALORES DEMONSTRADOS ACIMA INCLUEM REMUNERACOES PERCEBIDAS PELO SERVIDOR NO SEU ORGAO/EMPRESA DE ORIGEM']
Portal da Transparência: Recebeu duas vezes da INFRAERO, totalizando 7877,14
    
#02/2016
#Caso 1
Total de honorários: 3423.78
    [2016 2 1114862 '***.476.701-**' 'CARLOS AUGUSTO MOREIRA ARAUJO'
     'BANCO DA AMAZÔNIA S.A. - BASA' 3423.78]
Tupla na remuneração: 6847,56
    [2016 2 1114862 '***.476.701-**' 'CARLOS AUGUSTO MOREIRA ARAUJO' '26523,92'
 '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '-5673,36' '0,00' '-2353,02' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '18497,54' '0,00' '680,70' '0,00' '0,00' '0,00' '680,70'
 '0,00' '6847,56']
Obs: Não possui registro no arquivo de observações
Portal da Transparência: Recebe duas vezes do Banco da Amazonia, totalizando 6847,56.

#Caso 2
Total de honorários: 3938.57
    [2016 2 1982053 '***.452.781-**' 'SERGIO CRUZ'
 'EMPRESA BRASILEIRA DE INFRAESTRUTURA AEROPORTUÁRIA - INFRAERO' 3938.57]
Tupla na remuneração: 7877,14
    [2016 2 1982053 '***.452.781-**' 'SERGIO CRUZ' '28132,10' '0,00' '0,00'
 '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '-6115,60'
 '0,00' '-2353,02' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '19663,48' '0,00' '676,98' '0,00' '0,00' '0,00' '676,98' '0,00' '7877,14']
Obs: Ele possui observação referente a remuneração
    [2016 2 1982053 '***.452.781-**' 'SERGIO CRUZ'
 'OS VALORES DEMONSTRADOS ACIMA INCLUEM REMUNERACOES PERCEBIDAS PELO SERVIDOR NO SEU ORGAO/EMPRESA DE ORIGEM']
Portal da Transparência: Recebe duas vezes da INFRAERO

# 04/2016
# Caso 1
Total de honorários: 6105.27
    [2016 4 1102792 '***.132.251-**' 'IEDA APARECIDA DE MOURA'
     'SERVIÇO FEDERAL DE PROCESSAMENTO DE DADOS - SERPRO' 3504.74]
    [2016 4 1102792 '***.132.251-**' 'IEDA APARECIDA DE MOURA'
     'VALEC - ENGENHARIA CONSTRUÇÕES E FERROVIAS S.A.' 2600.53]
Tupla na remunaração: 8705,80
    [2016 4 1102792 '***.132.251-**' 'IEDA APARECIDA DE MOURA' '29257,94'
 '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '-7210,57' '0,00' '-2476,86' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '19570,51' '0,00' '458,00' '0,00' '0,00' '0,00' '458,00'
 '0,00' '8705,80']
Obs: Não possui registro no arquivo de observações
Portal da Transparência: Recebe duas vezes VALEC e uma da SERPRO, totalizando 8705,80 

#Caso 2
Total de honorários: 4645.92
    [2016 4 1293368 '***.195.641-**' 'ANELIZE LENZI RUAS DE ALMEIDA'
         'CAIXA ECONÔMICA FEDERAL - CAIXA' 4645.92]
Tupla na remunaração: 9291,84
    [2016 4 1293368 '***.195.641-**' 'ANELIZE LENZI RUAS DE ALMEIDA' '29257,94'
 '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '-6443,29' '0,00' '-2476,86' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '20337,79' '0,00' '458,00' '0,00' '0,00' '0,00' '458,00'
 '0,00' '9291,84']
Obs:Não possui registro no arquivo de observações
Portal da Tranparência: Recebe duas vezes da CAIXA ECONÔMICA 
        

# 08/2016:
Total de honorários: 7984.9
    [2016 8 1498874 '***.543.988-**' 'MAXIMILIANO SALVADORI MARTINHAO'
         'TELECOMUNICAÇÕES BRASILEIRAS S.A. - TELEBRAS' 3911.57]
    [2016 8 1498874 '***.543.988-**' 'MAXIMILIANO SALVADORI MARTINHAO'
         'VISIONA TECNOLOGIA ESPACIAL S.A' 4073.33]
Tupla na remunaração: 11896,47
    [2016 8 1498874 '***.543.988-**' 'MAXIMILIANO SALVADORI MARTINHAO'
 '27456,98' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '-6118,30' '0,00' '-2047,24' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '0,00' '19291,44' '0,00' '458,00' '0,00' '0,00' '0,00'
 '458,00' '0,00' '11896,47']
Observação: Possui registro no arquivo de observações
    [2016 8 1498874 '***.543.988-**' 'MAXIMILIANO SALVADORI MARTINHAO'
 'OS VALORES DEMONSTRADOS ACIMA INCLUEM REMUNERACOES PERCEBIDAS PELO SERVIDOR NO SEU ORGAO/EMPRESA DE ORIGEM']
Portal da Transparência: Recebe duas vezes da TELEBRAS e uma vez da VISIONA TECNOLOGIA ESPACIAL, totalizando 11896,47

# 10/2016:
Total de honorários: 3191.73
    [2016 10 1828300 '***.519.450-**' 'MANOEL AUGUSTO CARDOSO DA FONSECA'
         'CENTRO NACIONAL DE TECNOLOGIA ELETRÔNICA AVANÇADA S.A. - CEITEC' 3191.73]
Tupla na remunaração: 6383,46
    [2016 10 1828300 '***.519.450-**' 'MANOEL AUGUSTO CARDOSO DA FONSECA'
 '22796,57' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '-5699,48' '0,00' '-1911,95' '0,00' '0,00' '0,00' '0,00'
 '0,00' '0,00' '0,00' '15185,14' '0,00' '703,47' '0,00' '0,00' '0,00'
 '703,47' '0,00' '6383,46']
Obs: Não possui registro no arquivo de observações
Portal da Tranparência: Recebeu duas vezes da CEITEC, totalizando 6383,46




Mês/Ano |Servidor|Total de Honorários | Total de honorários do arquivo de remuneração | Observação (Arquivo de Observações) | Justificativa mostrada no portal da tranparência
------------ | -------------
01/2016 |CARLOS AUGUSTO MOREIRA ARAUJO| 3423.78|6847,56|Não possui registro no arquivo de observações|Recebeu duas vezes do banco da Amazônia, o que totaliza os 6847,56.
01/2016 |MARCELO DE SIQUEIRA FREITAS|8051.68|12191,79|Ele possui observação referente a remuneração*|Recebeu duas vezes da DATAPREV e uma da TELEBRAS, totalizando 12191,79
01/2016|SERGIO CRUZ|3938.57|7877,14|Ele possui observação referente a remuneração*|Recebeu duas vezes da INFRAERO, totalizando 7877,14
02/2016|CARLOS AUGUSTO MOREIRA ARAUJO|3423.78|6847,56|Não possui registro no arquivo de observações|Recebe duas vezes do Banco da Amazonia, totalizando 6847,56.
02/2016|SERGIO CRUZ|3938.57|7877,14|Ele possui observação referente a remuneração*|Recebe duas vezes da INFRAERO
04/2016|IEDA APARECIDA DE MOURA|6105.27|8705,80|Não possui registro no arquivo de observações|Recebe duas vezes VALEC e uma da SERPRO, totalizando 8705,80 
04/2016|ANELIZE LENZI RUAS DE ALMEIDA|4645.92|9291,84|Não possui registro no arquivo de observações|Recebe duas vezes da CAIXA ECONÔMICA
08/2016|MAXIMILIANO SALVADORI MARTINHAO|7984.9|11896,47|Possui registro no arquivo de observações*| Recebe duas vezes da TELEBRAS e uma vez da VISIONA TECNOLOGIA ESPACIAL, totalizando 11896,47
10/2016|MANOEL AUGUSTO CARDOSO DA FONSECA|3191.73|6383,46|Não possui registro no arquivo de observações|Recebeu duas vezes da CEITEC, totalizando 6383,46


*No arquivo de observações consta a seguinte observação:"OS VALORES DEMONSTRADOS ACIMA INCLUEM REMUNERACOES PERCEBIDAS PELO SERVIDOR NO SEU ORGAO/EMPRESA DE ORIGEM"

In [39]:
cadastro = pd.read_csv('../datas/2016/201612_Servidores/20161231_',encoding='iso-8859-1',delimiter='\t')

In [40]:
cadastro.head()

ANO  MES  ID_SERVIDOR_PORTAL             CPF  \
0  2016   12             1003998  ***.641.298-**   
1  2016   12             1007140  ***.005.336-**   
2  2016   12             1008777  ***.059.377-**   
3  2016   12             1009387  ***.583.280-**   
4  2016   12             1009579  ***.600.711-**   

                                   NOME  \
0                MARCUS VINICIUS SINVAL   
1  RODRIGO FONTENELLE DE ARAUJO MIRANDA   
2                          HO YIU CHENG   
3                   JANE FRAGA TUTIKIAN   
4                       BRUNO NUNES SAD   

                                             EMPRESA    VALOR  
0           EMPRESA BRASIL DE COMUNICAÇÃO S.A. - EBC  2807.90  
1          INDÚSTRIAS NUCLEARES DO BRASIL S.A. - INB  3376.30  
2     EMPRESA DE PLANEJAMENTO E LOGÍSTICA S.A. - EPL  3171.38  
3        HOSPITAL DE CLÍNICAS DE PORTO ALEGRE - HCPA  3248.21  
4  BB ADMINISTRADORA DE CONSÓRCIOS S.A. - BB CONS...  3120.83

In [8]:
for c in cadastro.values:
    for v in c:
        if not isinstance(v, int) and not isinstance(v, float):
            if "ABADIA CANDIDA LEMES" in v:
                print(c)

[1136025 'ABADIA CANDIDA LEMES' '***.834.461-**' '010****'
 'GUARDA DE ENDEMIAS' 'S' "''" 'III' "''" "''" "''" "''" "''" "''" "''"
 '25000000002410' 'SUS/MUNICIPAL - GO' 25000 'MINISTERIO DA SAUDE' 25000
 'MINISTERIO DA SAUDE' "''" "''" 99991 'ESTADOS / MUNICIPIOS / EMPRESAS'
 99991 'ESTADOS / MUNICIPIOS / EMPRESAS' 2 'CEDIDO SUS/LEI 8270'
 'Não informada' 'Não informada' 'REGIME JURIDICO UNICO'
 '40 HORAS SEMANAIS' '02/01/2007' "''" '29/06/2010' '000000019'
 '06/02/1987' "''" 'PORTARIA' 'CONTRATO' "''"]


In [41]:
afastamento = {}

In [42]:
for c in cadastro.values:
    ind = str(c[0])+","+str(c[1])+','+str(c[2])
    if ind in afastamento:
        afastamento[ind] += 1
    else:
        afastamento[ind] = 1

In [38]:
for i in afastamento.values():
    if i > 1:
        print(i)

In [43]:
afastamento

{'2016,12,1003998': 1,
 '2016,12,1007140': 1,
 '2016,12,1008777': 1,
 '2016,12,1009387': 1,
 '2016,12,1009579': 1,
 '2016,12,1015714': 1,
 '2016,12,1019200': 1,
 '2016,12,1020761': 1,
 '2016,12,1023817': 1,
 '2016,12,1026351': 1,
 '2016,12,1028846': 2,
 '2016,12,1032519': 1,
 '2016,12,1033836': 1,
 '2016,12,1036914': 1,
 '2016,12,1038276': 1,
 '2016,12,1041308': 1,
 '2016,12,1055838': 2,
 '2016,12,1059756': 2,
 '2016,12,1066507': 1,
 '2016,12,1066808': 1,
 '2016,12,1074231': 1,
 '2016,12,1081739': 1,
 '2016,12,1082827': 1,
 '2016,12,1090168': 1,
 '2016,12,1094304': 1,
 '2016,12,1100859': 1,
 '2016,12,1102792': 2,
 '2016,12,1103057': 1,
 '2016,12,1108007': 1,
 '2016,12,1108744': 1,
 '2016,12,1111737': 1,
 '2016,12,1114862': 1,
 '2016,12,1116221': 1,
 '2016,12,1116681': 1,
 '2016,12,1117424': 1,
 '2016,12,1118236': 1,
 '2016,12,1121126': 1,
 '2016,12,1123274': 1,
 '2016,12,1125079': 1,
 '2016,12,1131823': 1,
 '2016,12,1134179': 1,
 '2016,12,1135194': 1,
 '2016,12,1136349': 1,
 '2016,12,1

In [4]:
csv

Id_SERVIDOR_PORTAL                                         NOME  \
0                  1000000                         PAULO MARTINS SOARES   
1                  1000000                         PAULO MARTINS SOARES   
2                  1000001                               ANALIA BATISTA   
3                  1000002                          ARY DE NOROES FILHO   
4                  1000003                       EDUARDO BRUNO OLIVEIRA   
5                  1000004                 MOISES ALBERTO CALLE AGUIRRE   
6                  1000005                     LAURA JANAINA DIAS AMATO   
7                  1000010            DANIELLE CHAVES GONCALVES TAVARES   
8                  1000011              JOSE EDSON CESAR DE ALBUQUERQUE   
9                  1000012                       CINTIA FLORENCIO ALVES   
10                 1000015                      ANA CRISTINA PINTO REIS   
11                 1000016                 ELIANE PAVESI BARRETO SOARES   
12                 1000017                JORGE LUIZ DE OLIVEIRA VIEIRA   
13                 1000018                       LENA CAVALCANTE FALCAO   
14                 1000018                       LENA CAVALCANTE FALCAO   
15                 1000020                              ADELMO GOLYNSKI   
16                 1000021               MARIA AUREA DOS SANTOS RIBEIRO   
17                 1000023                       VALMI SILVA NASCIMENTO   
18                 1000023                       VALMI SILVA NASCIMENTO   
19                 1000029                    FERNANDO MORAIS RODRIGUES   
20                 1000029                    FERNANDO MORAIS RODRIGUES   
21                 1000030                 LEILA MARIA DOS SANTOS ALVES   
22                 1000031               ROGERIO ANTONIO DA SILVA MATOS   
23                 1000032                      EDMILSON ALVES DA SILVA   
24                 1000033                        MARISE SILVA SIQUEIRA   
25                 1000033                        MARISE SILVA SIQUEIRA   
26                 1000034                   GILSON FLORINDO DOS SANTOS   
27                 1000034                   GILSON FLORINDO DOS SANTOS   
28                 1000040                    FERNANDA MACHADO FERREIRA   
29                 1000041                       MAYSA DO VALE OLIVEIRA   
...                    ...                                          ...   
808150             2260341                        JONAS MENDES OLIVEIRA   
808151             2260342              JULIA RODRIGUES MARCONDES DUTRA   
808152             2260343                   BRUNA CARMINATTI BAVARESCO   
808153             2260344                       JULIANA NUNES FERREIRA   
808154             2260345                     LUMA LIMA E SILVA SANTOS   
808155             2260346                    CORA SALLES MARURI CORREA   
808156             2260347    LUCIANA FERREIRA JOB VASCONCELOS DA SILVA   
808157             2260348                       MARCOS VINICIOS RAZERA   
808158             2260349                   FRANCIELE VILANOVA RIBEIRO   
808159             2260350             NAIRANA RADTKE CANEPPELE BUSSLER   
808160             2260351                FERNANDA DAYANA DA SILVA DIAS   
808161             2260352                     LARISSA DE OLIVEIRA CRUZ   
808162             2260353               DANIEL NEEMIAS TORRES SIQUEIRA   
808163             2260354                 RODRIGO DA SILVA ALBUQUERQUE   
808164             2260355                            ALICE FONTE BASSO   
808165             2260356                            JULIANA BRAGHETTO   
808166             2260357                      LILIAN NUNES DOS SANTOS   
808167             2260358                CASSIO DANIEL ARAUJO DA SILVA   
808168             2260359                         LUCAS SILVA OLIVEIRA   
808169             2260360                       RENATA SBERSE BERNARDI   
808170             2260361                     ROSIMEIRE MUNDOCO CORREA   
808171             2260362       

In [4]:
csv = pd.read_csv('../datas/2017/201701_Servidores/20170131_NewCadastro.csv',encoding='iso-8859-1',delimiter=';')

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [5]:
csv.head(10)

Id_SERVIDOR_PORTAL                               NOME             CPF  \
0             1000000               PAULO MARTINS SOARES  ***.787.200-**   
1             1000000               PAULO MARTINS SOARES  ***.787.200-**   
2             1000001                     ANALIA BATISTA  ***.600.796-**   
3             1000002                ARY DE NOROES FILHO  ***.124.863-**   
4             1000003             EDUARDO BRUNO OLIVEIRA  ***.243.821-**   
5             1000004       MOISES ALBERTO CALLE AGUIRRE  ***.122.446-**   
6             1000005           LAURA JANAINA DIAS AMATO  ***.761.819-**   
7             1000010  DANIELLE CHAVES GONCALVES TAVARES  ***.956.267-**   
8             1000011    JOSE EDSON CESAR DE ALBUQUERQUE  ***.519.384-**   
9             1000012             CINTIA FLORENCIO ALVES  ***.326.633-**   

  MATRICULA                        DESCRICAO_CARGO CLASSE_CARGO  \
0   002****                                     ''           ''   
1   002****              TECNICO EM ARTES GRAFICAS            D   
2   006****     ASSISTENTE EM CIENCIA E TECNOLOGIA            R   
3   005****                AGENTE DE SAUDE PUBLICA            S   
4   015****                             ANALISTA-A            A   
5   016****       PROFESSOR DO MAGISTERIO SUPERIOR            6   
6   014****       PROFESSOR DO MAGISTERIO SUPERIOR            6   
7   021****           TEC EM SEGURANCA DO TRABALHO            D   
8   001****  AGENTE DE POL FEDERAL CLASSE ESPECIAL           ''   
9   018****  ESCRIVAO DE POLICIA FEDERAL 2A CLASSE           ''   

  REFERENCIA_CARGO PADRAO_CARGO NIVEL_CARGO SIGLA_FUNCAO  ...   \
0               ''           ''          ''           FG  ...    
1               ''          414          ''           ''  ...    
2               ''          III          ''           ''  ...    
3               ''          III          ''           ''  ...    
4               ''           ''         006           ''  ...    
5               ''           ''         604           ''  ...    
6               ''           ''         602           ''  ...    
7               ''          201          ''           ''  ...    
8               ''           ''          ''           ''  ...    
9               ''           ''          ''           ''  ...    

  DATA_NOMEACAO_CARGOFUNCAO DATA_INGRESSO_ORGAO  \
0                        ''          29/12/2008   
1                        ''          29/12/2008   
2                        ''          20/08/1979   
3                        ''          29/06/2010   
4                        ''          03/04/2007   
5                        ''          13/03/2009   
6                        ''          12/01/2010   
7                        ''          10/12/2014   
8                        ''          05/06/2007   
9                        ''          22/07/2010   

  DOCUMENTO_INGRESSO_SERVICOPUBLICO DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO  \
0                         000046/92                           22/01/1992   
1                         000046/92                           22/01/1992   
2                         000000001                           20/08/1979   
3                         000000324                           01/06/1983   
4                                SN                           03/04/2007   
5                               128                           13/03/2009   
6                              5244                           21/05/2004   
7                               492                           28/01/2015   
8                            910/MJ                           07/01/1986   
9                              1236                           22/07/2010   

  DIPLOMA_INGRESSO_CARGOFUNCAO DIPLOMA_INGRESSO_ORGAO  \
0                           ''                    LEI   
1                           ''                    LEI   
2                           ''               PORTARIA   
3                           ''               PORTARIA   
4                

In [26]:
csv.COD_UORG_EXERCICIO.tolist()[3] == "''"

True

In [30]:
csv = pd.read_csv('../datas/2017/201701_Servidores/20170131_NewCadastro.csv',encoding='iso-8859-1',delimiter=';')

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,12,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [29]:
print(len(csv.COD_UORG_EXERCICIO.tolist()))
a = 0
for c in csv.COD_UORG_EXERCICIO.tolist():
    if pd.isnull(c):
        a += 1
print(a)

805734
171185


In [11]:
csv.columns

Index(['Id_SERVIDOR_PORTAL', 'NOME', 'CPF', 'MATRICULA', 'DESCRICAO_CARGO',
       'CLASSE_CARGO', 'REFERENCIA_CARGO', 'PADRAO_CARGO', 'NIVEL_CARGO',
       'SIGLA_FUNCAO', 'NIVEL_FUNCAO', 'FUNCAO', 'CODIGO_ATIVIDADE',
       'ATIVIDADE', 'OPCAO_PARCIAL', 'COD_UORG_LOTACAO', 'UORG_LOTACAO',
       'COD_ORG_LOTACAO', 'ORG_LOTACAO', 'COD_ORGSUP_LOTACAO',
       'ORGSUP_LOTACAO', 'COD_UORG_EXERCICIO', 'UORG_EXERCICIO',
       'COD_ORG_EXERCICIO', 'ORG_EXERCICIO', 'COD_ORGSUP_EXERCICIO',
       'ORGSUP_EXERCICIO', 'TIPO_VINCULO', 'SITUACAO_VINCULO',
       'DATA_INICIO_AFASTAMENTO', 'DATA_TERMINO_AFASTAMENTO',
       'REGIME_JURIDICO', 'JORNADA_DE_TRABALHO', 'DATA_INGRESSO_CARGOFUNCAO',
       'DATA_NOMEACAO_CARGOFUNCAO', 'DATA_INGRESSO_ORGAO',
       'DOCUMENTO_INGRESSO_SERVICOPUBLICO',
       'DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO', 'DIPLOMA_INGRESSO_CARGOFUNCAO',
       'DIPLOMA_INGRESSO_ORGAO', 'DIPLOMA_INGRESSO_SERVICOPUBLICO',
       'UF_EXERCICIO'],
      dtype='object')

In [15]:
# FUNÇÃO + CODIGO_ATIVIDADE
# csv.values[50][11] +' '+ str(csv.values[50][12])

'CARGO DE  DIRECAO - CD - IFES nan'

In [21]:
# MÊS DE JANEIRO - 2017
i = 0
n = {}
for c in csv.values:
    if(pd.isnull(c[11]) == False and pd.isnull(c[12])):
        if c[11] in n:
            n[c[11]]['Qtd'] += 1
        else:
            n[c[11]] = {'Qtd':1}
        i += 1
print(n)

{'CARGO DE  DIRECAO - CD - IFES': {'Qtd': 4}, 'GRATIFICACAO DE FUNCAO DE CONFIANCA': {'Qtd': 948}, 'DIRECAO E ASSESSORAMENTO SUPERIOR': {'Qtd': 62}}


In [15]:
n

['0033:COORDENADOR',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 '0045:CHEFE DE SERVICO',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 '0094:FUNCAO GRATIFICADA',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 '0017:DIRETOR ADJUNTO',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 '2043:CHEFE',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 '2038:COORDENADOR',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 '2043:CHEFE',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 'nan:nan',
 '1115:COORDENADOR DE GRADUACAO',
 'nan:nan',

In [16]:
for i in n:
    if i.split(":")[0] == '0033':
        print(i)

0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENAD

0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENAD

0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENAD

0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENAD

0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENADOR
0033:COORDENAD

In [17]:
len(csv.values)

805734

In [18]:
#MẼS DE FEVEREIRO - 2017
i = 0
for c in csv.values:
    if(pd.isnull(c[11]) == False and pd.isnull(c[12])):
        print(c)
        i += 1
print(i)

0


In [19]:
len(csv.values)

804620

In [21]:
#MẼS DE MARÇO - 2017
i = 0
for c in csv.values:
    if(pd.isnull(c[11]) == False and pd.isnull(c[12])):
        print(c)
        i += 1
print(i)

0


In [11]:
len(csv.values)

808180

In [118]:
cods_str = []

#i = 0
#n = {}
#print("2016")
#Todos os cargos de 2016
for d in os.listdir('../datas/2016/'):
    for c in os.listdir('../datas/2016/'+d):
        if '_Cadastro.csv' in c:
            print('../datas/2016/'+d+'/'+c)
            crg = pd.read_csv('../datas/2016/'+d+'/'+c,encoding='iso-8859-1',delimiter='\t')
            crg.head(5)
            #for cargo in crg.DESCRICAO_CARGO.values:
                #if cargo not in all_cargos:
                    #all_cargos.append(cargo)
            #for c in crg.values:
                #if(pd.isnull(c[11]) == False and pd.isnull(c[12])):
                    #if c[11] in n:
                        #n[c[11]]['Qtd'] += 1
                    #else:
                        #n[c[11]] = {'Qtd':1}
                    #i += 1
            #print(n)
            cods = {}
            for c in crg.CODIGO_ATIVIDADE:
                if c in cods:
                    cods[c]['Qtd'] += 1
                else:
                    cods[c] = {'Qtd':1}
                    
            keys = list(cods.keys())
            for k in range(len(keys)):
                try:
                    keys[k] = int(keys[k])
                except:
                    if pd.isnull(keys[k]) == False:
                        cods_str.append(keys[k])
                        #print(keys[k])
            
#print("2017")
#Todos os cargos de 2017
'''for d in os.listdir('../datas/2017/'):
    for c in os.listdir('../datas/2017/'+d):
        if 'Cadastro2' in c:
            crg = pd.read_csv('../datas/2017/'+d+'/'+c,encoding='iso-8859-1',delimiter='#')
            #for cargo in crg.DESCRICAO_CARGO.values:
                #if cargo not in all_cargos:
                    #all_cargos.append(cargo)
            for c in crg.values:
                if(pd.isnull(c[11]) == False and pd.isnull(c[12])):
                    if c[11] in n:
                        n[c[11]]['Qtd'] += 1
                    else:
                        n[c[11]] = {'Qtd':1}
                    i += 1
            print(n)'''

../datas/2016/201603_Servidores/20160331_Cadastro.csv


/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


../datas/2016/201601_Servidores/20160131_Cadastro.csv
../datas/2016/201607_Servidores/20160731_Cadastro.csv
../datas/2016/201604_Servidores/20160430_Cadastro.csv
../datas/2016/201608_Servidores/20160831_Cadastro.csv
../datas/2016/201611_Servidores/20161130_Cadastro.csv
../datas/2016/201605_Servidores/20160531_Cadastro.csv
../datas/2016/201602_Servidores/20160229_Cadastro.csv
../datas/2016/201610_Servidores/20161031_Cadastro.csv
../datas/2016/201612_Servidores/20161231_Cadastro.csv
../datas/2016/201606_Servidores/20160630_Cadastro.csv
../datas/2016/201609_Servidores/20160930_Cadastro.csv


"for d in os.listdir('../datas/2017/'):\n    for c in os.listdir('../datas/2017/'+d):\n        if 'Cadastro2' in c:\n            crg = pd.read_csv('../datas/2017/'+d+'/'+c,encoding='iso-8859-1',delimiter='#')\n            #for cargo in crg.DESCRICAO_CARGO.values:\n                #if cargo not in all_cargos:\n                    #all_cargos.append(cargo)\n            for c in crg.values:\n                if(pd.isnull(c[11]) == False and pd.isnull(c[12])):\n                    if c[11] in n:\n                        n[c[11]]['Qtd'] += 1\n                    else:\n                        n[c[11]] = {'Qtd':1}\n                    i += 1\n            print(n)"

In [62]:
import re

In [77]:
letters = re.findall('[a-zA-Z]+','FDA1') #retorna só as letras
numbers = re.findall('[0-9]+','FDA1987968') #retorna só os números

#Hash a partir dos caracteres
cod = ""
for l in range(len(letters[0])):
    cod += str(ord(letters[0][l]))
print(str(cod)+" "+str(int(numbers[0])))

706865 1987968


In [94]:
cods_str = []

In [103]:
cods = {}
for c in csv.CODIGO_ATIVIDADE:
    if c in cods:
        cods[c]['Qtd'] += 1
    else:
        cods[c] = {'Qtd':1}

In [104]:
#Outro problema, CODIGO_ATIVIDADE possue letras com números (ex.: FD01), além dos valores nulos
keys = list(cods.keys())
#keys[1] = '0000'

for k in range(len(keys)):
    try:
        keys[k] = int(keys[k])
    except:
        if pd.isnull(keys[k]) == False:
            cods_str.append(keys[k])
            print(keys[k])

FDO1
FCA3
FDJ1
FDE2
FCA4
FST2
FCA2
FDT1
FST1
FDE1
FDG1
FDS1
FCA1


In [92]:
for c in cods_str:
    if pd.isnull(c):
        cods_str.remove(c)

In [119]:
cods_dic = {}
for c in cods_str:
    if c in cods_dic:
        cods_dic[c]['Qtd'] += 1
    else:
        cods_dic[c] = {'Qtd':1}

In [120]:
# CÓDIGOS COM LETRAS EM CODIGO_ATIVIDADE
cods_dic

{"''": {'Qtd': 12},
 'FCA1': {'Qtd': 12},
 'FCA2': {'Qtd': 12},
 'FCA3': {'Qtd': 12},
 'FCA4': {'Qtd': 12},
 'FDE1': {'Qtd': 12},
 'FDE2': {'Qtd': 12},
 'FDG1': {'Qtd': 12},
 'FDJ1': {'Qtd': 12},
 'FDO1': {'Qtd': 12},
 'FDS1': {'Qtd': 12},
 'FDT1': {'Qtd': 12},
 'FST1': {'Qtd': 12},
 'FST2': {'Qtd': 12}}

In [5]:
#Verificando nível_funcao
niveis = []
for n in csv.NIVEL_FUNCAO.values:
    try:
        nivel = int(n)
        print(nivel)
    except:
        if pd.isnull(n) == False:
            niveis.append(n)

4
1011
1
17
1
2
4
4
1
3
4
11
6
2
1011
2
1
3
1022
3
2
1
1
4
1
1012
5
1
1
1011
4
2
2
3
1012
5
1
1
1
1
1011
2
1
3
2
5
1
2
5
8
1
1
1013
1
4
1
4
1
5
1011
3
1
3
1
4
1014
1015
3
1
2
2
4
4
1013
1
2
1
1
3
3
2
1
2
1
2
1023
5
1
2
1
4
1
2
3
1015
3
4
4
1
1
1
8
2
1
1
1013
2
2
1012
5
1
2
1014
2
1
2
2
1012
2
3
2
4
2
2
3
1
1
1
4
5
1212
25
1011
1
2
2
1015
2
3
1
6
3
1
1023
2
4
5
1014
1
1011
2
2
1
1
4
1012
1
2
4
1
3
5
19
1
1011
1
4
2
29
3
1
21
2
8
1
2
27
1
3
1
2
3
14
4
1012
7
1
1
1
1
1012
2
2
2
3
1
1
1
1
1
1
1
3
1
1014
8
35
4
2
1
3
2
1
1014
1013
7
1
1
1
3
3
1
3
7
3
1014
1011
7
2
1012
1012
1023
14
2
4
2
1011
13
19
1
1
1
4
1015
2
1
4
1012
17
2
14
2
3
14
3
1
1
1014
10
3
3
1013
1
1
1
4
12
1022
1
1014
1
2
1
2
5
1013
1011
1
1
36
1
1
3
1
26
4
1
4
5
1015
1
1
4
1011
4
2
1
4
1014
1
27
1
3
1011
1014
1
1012
2
1015
1
1012
1
1022
6
1021
2
1
26
3
2
26
2
2
2
1
29
1011
1011
1
1
3
1024
1
7
3
5
1
5
4
4
2
2
2
1
2
1
1025
1021
3
1011
2
1
1
1
1
1
2
2
1
2
2
4
1
1
1
11
1011
1
4
2
1
2
3
1011
1022
1
1
2
1
1021
4
1012
1014
4
1
4
101

1
1014
1022
2
2
7
26
2
3
1
1
1
7
1
3
3
2
3
2
2
1014
1013
7
1022
3
6
1011
5
3
1
1022
2
1
1
1
1013
1
10
5
1
1013
6
4
1
2
3
7
26
3
1012
1012
3
4
2
2
1
1
5
1
1013
1
14
2
7
1014
1
1012
1
2
2
1
1023
14
3
5
1
1
1
1
1
5
3
4
3
5
1
2
4
2
1
2
1
2
1
1
1011
1023
5
3
2
17
1015
3
1
1
2
1
2
23
2
1
9
6
17
4
5
3
1
1012
2
1
1013
1
1013
1011
1
3
1012
1012
7
4
1011
1
2
1
1
3
4
1
4
1015
4
1
1
1
1
1
1
1
3
4
5
10
1
2
2
1013
1013
28
18
3
1011
2
2
3
4
1
2
4
3
3
1015
4
2
3
3
1
1
3
1012
2
3
1011
4
1
1
1012
3
1013
1
1
8
4
2
1
5
4
13
1
1022
2
1
1
6
1014
1013
1
7
3
1022
3
1021
1
1
39
4
3
1
1
1
2
1011
1013
5
1
2
3
1
1
1
1023
13
1
2
1
2
1
1
1011
5
3
1
26
4
1
19
1023
1
3
1
1
1
1
1011
1
27
1
1
2
2
1012
6
1014
4
2
4
1
1
1
1
4
2
1013
4
1011
2
1
1022
1012
1
2
1
1011
1
1
1014
1
1
1012
1014
1
1
2
1
2
1011
1
11
4
2
1011
4
1011
1012
10
1
2
1
3
1012
4
1012
1014
2
2
1
8
24
1
1013
1
1
17
1
7
4
1
3
1
1
1
1
27
6
3
1
1022
1021
3
1013
1014
1
3
1
1
1012
1
5
1011
1
1013
1012
1012
3
2
4
21
5
5
3
1
2
1
1
3
1
3
4
1011
15
35
2
1
1
4
4
7
1


1012
4
1
3
4
1
2
1
2
1014
2
1
7
4
1
2
1
6
27
1012
1021
3
3
5
1
1
5
1
6
3
8
1
1011
1
1
1
4
4
1021
1014
2
2
1
1
3
1
2
4
7
4
1
1
7
1012
1012
1
1
1
3
1
1012
3
1
1
1
3
4
2
2
1
4
27
1
2
3
1
12
1
1
1
1
3
7
7
1013
2
1011
5
1013
2
1
1
4
1
1
1
1
1013
1
1012
6
1022
1
1
1011
5
2
1
1011
1014
3
4
1011
2
4
2
2
1
2
1012
1
1012
4
2
1
1022
1
4
4
2
4
1014
1
2
1014
1
2
1
7
2
3
1015
1
1013
1014
10
4
3
1
6
2
2
1
1
1
3
10
3
1
2
1012
1
3
2
5
2
5
1
1011
2
1013
2
1
2
1
2
14
1011
1023
4
4
3
1
1
3
1011
6
6
4
4
1
1
2
1011
1
5
1
2
5
1212
2
1
2
1011
1011
1011
1
4
4
1
1
3
2
1
1024
1
1
12
1
1
1
3
3
4
1013
1
3
1
3
1
1
2
2
4
7
1
1
2
4
1011
27
1
2
50
1
4
2
1
2
4
4
1016
2
5
1
1
1
3
3
3
2
1
4
4
3
1014
26
2
5
1011
1
1011
1012
2
1011
3
1013
1
1
3
4
2
12
1
1014
2
1
25
4
1
1
1
1
1
1023
1012
1
3
4
1
4
8
1013
2
3
4
1
1
1013
4
2
5
1
1
4
1
7
4
2
11
1
1
3
2
3
1
1
1
37
2
2
1
1021
2
1012
1014
1013
4
5
6
6
5
1012
1
1012
3
4
1025
4
2
1
1
4
1
3
1014
1013
1014
9
2
4
2
1
1
1
3
3
1
2
3
27
1
6
1
4
4
1013
1
2
15
1
1
1012
3
3
3
2
3
5
1
2
1012

8
2
5
1021
1
1011
12
1012
3
5
1013
1013
1014
4
2
1
2
3
2
5
1
1022
3
1
2
1
1012
10
3
2
3
1
1
8
3
1013
3
1
4
4
13
2
3
1
2
1
1
1014
1014
1013
4
1014
1014
3
20
2
1012
1012
48
1011
1
3
1
1014
4
1012
1012
4
1
2
1
4
4
3
2
1023
2
8
2
1
1022
3
7
1011
4
1011
5
1
1012
1
1012
4
3
2
1
1012
1021
1212
4
4
4
2
1212
3
2
1013
1
1
25
1011
2
1
1011
2
4
1
6
1012
1011
1012
1
3
1
1
1011
1
1
3
1013
1014
1013
2
4
2
1013
1
1013
1
1
1
1
2
1
4
1015
1011
5
1
8
23
20
2
2
4
2
1021
4
1
6
1
3
1
27
5
2
1013
2
2
1
9
3
1011
25
1012
4
1
1
3
5
1
1013
1
1
1
2
1
1
1025
2
6
2
3
1
1011
1014
1
1
1
1015
7
3
2
2
1
1022
3
4
1012
4
2
2
1021
1022
1011
3
1
21
1
1014
26
1011
1
3
1
1012
4
1
1
1011
1012
1
1212
3
1
1
1
1
1
2
27
4
2
3
1
1
1
4
2
1
3
3
1
7
1023
3
2
1
2
1
1022
2
1
1022
1
2
7
7
1
18
4
1
1
1021
7
2
3
1
1024
3
1
7
1
3
1
4
1022
1025
4
1
1
3
1
1
1011
1
22
4
4
1023
1
1
2
1
2
2
1
4
1
1
5
1012
1
1014
1011
1
2
2
1
1
1
1
3
2
2
1014
2
1013
1
1
3
2
2
3
1
1
27
2
1
3
21
1
13
14
4
1
24
1015
1012
4
2
1
25
1014
4
1
4
1
1
1
1
1014
1012
1
2
11

1
3
8
1011
1
1
1
2
1011
3
1
1021
1012
1
5
2
6
1
1
1012
3
1011
3
13
4
7
1021
1
11
2
2
1
2
1
3
2
1
4
3
1
2
1
1
1
1013
4
2
1013
1013
8
1015
1
2
1
4
4
5
1
5
2
4
1
2
26
1011
2
1011
2
3
1
4
1
1
1011
1014
1024
1
3
1
1
3
31
2
1011
1
1
1
1
1014
5
1023
4
1013
23
5
1
4
1
28
4
1
1
5
1
1014
1
1
1
1
2
1015
3
3
10
1
1021
1
10
1
1
4
1022
1
1
1
1
1013
27
1
1025
1
1
1
2
2
12
6
2
4
2
4
4
1013
1
1013
1
1
6
3
2
7
4
4
1021
7
1011
2
1
1
1014
3
5
2
1
1012
8
2
2
2
1011
27
6
1011
3
3
1015
1
1
1
1012
2
1011
4
1
1012
1
1
1
1
11
1
2
2
43
1
1011
1011
4
1012
4
2
16
26
1011
1014
1
1
1
1
1011
4
1
2
1
1012
2
1
1013
1
3
1013
3
5
27
2
21
8
1
3
23
1015
27
1021
1013
4
3
1
3
27
4
1
1015
1
2
2
1
27
1
1013
1012
1
7
4
5
4
27
2
1
1014
4
2
2
2
7
51
30
3
4
2
7
1
5
1
1011
4
2
1013
1
2
1022
1
1
5
11
1012
1
1015
1
1
1
7
1
2
23
27
3
7
1
1012
1011
2
1011
3
6
1
5
2
1
3
1023
1022
2
4
4
1014
1
3
24
1
1
5
1012
1
1015
1
3
3
26
2
1
26
26
1
18
1014
1023
1
2
5
3
1
1
1
3
2
2
2
1
3
3
3
1
1011
1
1
3
2
2
1021
2
1021
7
1
23
3
1
1
3
1
1
1011
1011
2

3
3
1013
1
1
2
2
1012
7
1
1015
1
8
1
1013
18
5
1
3
1
7
2
10
17
1013
2
1
1022
2
17
2
7
1013
6
7
1
1022
2
6
16
3
1
1
1
1012
1
1
1
2
19
5
1011
24
5
18
2
25
2
7
1
1
3
26
2
3
1012
2
1
4
1
1
1
4
1
1011
1
2
6
1
3
1
1014
2
1
1
1
1013
1012
1212
2
4
1
4
1013
1
1
3
1
1
1011
1
3
1013
1
11
1011
7
1
1
1
1011
1
2
4
2
2
2
1
3
3
25
4
1013
4
1013
1021
6
3
1
2
1023
1012
3
4
1
1
1
1
3
1011
2
1
14
3
2
1021
1
2
13
1
4
1
4
2
1
1
1
1
9
3
1013
4
2
4
1
1015
1011
1012
1011
1
1
1021
1
1
1013
1014
2
7
3
1014
1
3
35
6
3
2
1
1
4
1
4
1
1022
2
2
15
1011
8
4
1011
1
3
4
2
4
1
1
1011
5
4
1
1
1
1
1
1014
2
1
2
3
1
1
26
1014
2
1
1021
1
3
2
1
1
1
2
1012
7
4
2
1
1011
1011
1
1
1
1011
5
1
1
11
3
1
3
1
1023
1
1011
2
1
4
4
2
1
1012
2
4
1
1015
3
4
1
17
4
1
2
4
2
3
1
3
1
5
7
1
1
1015
1011
2
2
1
1022
2
1
2
5
1
1
2
1011
2
1022
1
1014
1
5
1
1
4
4
1013
1
22
10
4
5
4
43
1013
11
1
3
3
1
3
2
36
5
27
1013
1
2
1
1
3
1011
14
1014
4
1
14
1
4
5
1011
1011
2
5
1
1
1
5
1012
1011
1
4
3
3
3
26
3
5
1
3
3
1
2
1
3
26
1
1
4
2
1
2
6
4
1
2
8
3
6
7
1
4
2


13
2
1021
2
2
1011
9
4
3
3
5
3
1
1
1
1022
1
4
1
1
3
23
2
4
2
3
1
4
1
1
2
2
4
1
1
3
3
4
1022
1011
2
1
5
1
1012
1
1021
3
1
4
1021
2
4
7
3
8
4
15
1
3
3
1012
1015
1
1
1
1
1
2
1022
2
1021
2
6
3
1
2
6
1
39
2
2
4
2
1
3
1
1212
1023
1011
52
1
3
1
1
1
1
1013
3
28
1
2
1
1
2
2
5
1011
2
1
1
1011
1013
2
2
4
1024
2
1023
2
5
3
1
1
1015
3
1013
2
3
1012
1012
1022
4
1012
1
1011
2
1013
1012
5
2
4
1013
2
4
1
1
4
1024
1
1
2
1025
2
2
1
1
4
1
5
5
1021
1
4
2
6
27
2
1011
2
5
1
25
1013
1
2
4
3
4
1014
1
2
1013
3
2
1
1
4
2
1022
1011
4
3
1
1
4
4
1013
1011
2
1013
5
4
1
1014
1011
1
1011
2
9
3
1
3
3
1
52
1022
1
22
1
27
1
1
10
1022
15
4
3
4
2
4
5
1
35
4
5
1
1013
1024
1011
1
4
5
4
4
1
1
5
1013
3
9
1
1012
1
2
24
1011
4
1
3
1
1
37
4
4
3
3
2
1
35
2
1
2
2
2
2
4
1
4
36
1
1015
5
1011
27
1
1012
28
1
26
1011
5
2
1
1
4
1
1013
2
6
7
10
1
3
1
1
5
1
4
1
1
1
1
1
2
1
1
5
1
4
11
1
2
27
1
5
3
1015
1011
1
21
6
1
27
1013
4
1
1
3
1
3
14
9
2
1012
11
2
2
1
1014
1
2
1023
4
1
1011
2
1
3
1022
21
5
12
11
1012
52
1
1
6
1
1
1
2
7
4
1014
1015
2
1


4
1
1
1011
3
4
2
1
1013
1011
1021
1
6
1014
1011
3
5
4
2
3
1
1012
1022
3
1
3
3
1022
1023
2
1014
3
4
1
4
4
4
2
1
1012
5
2
1
1013
2
2
4
2
27
2
4
1
4
1
1015
1
1
3
1
13
1
1022
2
1
7
1013
1
1
1
1
4
2
4
1
1
3
6
1012
1021
4
1
2
1
2
1012
1
5
5
7
1
2
1
1013
1
1
6
4
1023
7
11
4
4
3
25
1015
2
7
1
1022
4
1014
1015
1
3
1
1024
1013
2
1
3
1
4
1021
1012
1
2
1
5
4
3
1013
3
3
7
1012
1
39
2
27
3
1014
3
2
4
2
1
3
4
2
1
1011
3
1
2
4
1
1
1
3
2
4
4
7
1
1
1
4
1
1012
1012
4
7
3
1
7
1
4
1
1013
1
1
1
4
1
2
3
14
1
1
1013
1
2
2
1023
1
26
5
1
2
7
2
1
1014
1012
4
1
1014
43
1
28
48
1
2
1
1024
1
2
3
2
3
1
1
4
3
1
1
4
2
2
1
1
2
1
2
1012
3
1
2
1
1
1
2
3
1
27
5
1
4
1
1
1
3
1
8
4
2
1012
2
1
1
1011
1011
7
1012
1
1
1023
1011
1
2
1014
2
2
2
1012
27
3
26
1012
1024
1
1
2
4
1
8
25
1015
1012
2
1011
20
2
1023
1014
1
2
4
14
6
1013
1
2
7
14
1012
1
2
1012
1
6
1
3
4
1
1011
3
3
48
1
1
1011
22
2
1
1
1
3
1022
1
1
4
1
3
3
3
1011
4
1012
1
3
2
1
1
1
12
14
1
1
2
4
1
5
1
2
1
4
1012
25
2
4
3
1
4
1
1014
1
1
2
1
2
1015
4
1
25
1021
1022
4
9
1
1
1

1
2
4
1
27
4
7
3
4
4
1
1012
2
1
26
1212
8
1011
4
4
1
5
2
4
4
1022
1
1021
1012
5
1
1021
1
1014
5
1
1
2
1
2
3
1023
2
2
5
2
2
2
1
1012
1022
1014
1023
3
1012
2
1
1
1
3
1
3
1014
2
3
1
1
1
1013
3
1012
4
3
1013
2
7
4
2
4
5
1
1012
5
3
43
1
1
4
1
4
1015
2
5
4
2
2
3
2
1011
1
1
1023
3
1012
1011
1
2
6
1011
1011
1011
1011
1
27
1014
3
14
1
11
1011
2
7
1
1
4
1
1014
5
2
2
3
1012
2
1011
15
1012
2
1022
5
1012
1014
2
1
2
1024
1021
1
1
4
2
6
1013
2
10
4
1
1012
1
1
1
2
1
4
1
3
1012
1
4
1011
4
1
3
1023
1
3
4
1
7
2
1013
2
1015
12
1
2
3
1012
1013
1022
1
1
1
5
1
4
2
1012
2
2
1
2
2
3
3
4
5
7
1
3
1
1
3
2
24
1
4
1
2
1013
1
1011
3
3
1
1011
7
1011
1012
2
19
4
1013
1014
2
1
1
1011
1023
3
1011
4
52
1012
3
3
1013
2
1
5
2
25
1012
1014
1012
2
6
2
14
2
2
2
1
2
1014
3
1
1011
1
1012
2
1014
4
1
2
1014
36
1011
1024
14
1
24
25
1
4
4
6
1
1022
1012
1014
1011
1
1
2
5
51
3
26
1
4
2
1011
1212
1
6
4
3
1
4
1011
1
1011
6
5
2
3
3
4
26
5
1015
4
4
1
1013
3
2
5
4
2
1
1
1011
1
1
1
1
4
49
1
2
2
1
7
1011
24
4
5
1011
1011
2
3
1024
1011
2
5
1

1013
1014
1
1011
1011
1
1
3
52
1
1
4
1
1
4
1014
3
1
11
1011
1012
4
8
5
1
1
2
1012
1012
3
1011
1
2
3
3
3
4
6
1011
4
1
4
2
1011
1
1
1012
4
1013
1013
1
1011
1
7
3
4
1012
1
48
1
1012
1
14
3
1013
1011
6
1
1
2
1
1011
1
7
5
1
1
24
1011
1
2
2
2
2
3
1
1
2
1
1
1
5
5
1012
1
4
1
1
15
1011
2
1
2
3
5
1012
1012
1
1012
1
2
1
10
1
2
7
1
1
2
3
1
1022
2
1
2
2
13
1
4
2
1023
3
1
1012
1014
11
3
1011
1
2
5
2
4
1
1
2
2
1023
3
1
2
2
3
1
4
1012
4
1012
3
1
4
1
1
1011
1
1012
25
1013
1011
1
1021
2
21
2
1
1
1
1
6
3
10
1
6
1
1
4
8
1011
3
1011
5
9
1
1014
6
2
1
1011
1012
9
1
28
4
1
1
1013
1
1024
4
3
1
8
3
1012
6
2
3
1
1015
1
2
1012
3
1
1
1011
2
1014
4
5
4
1
1
4
3
2
1013
4
1
26
6
2
1
1012
1
4
1
4
2
4
1012
1
14
4
1
1
1012
1013
1
4
4
4
1
4
2
1
1022
1
4
1011
1
1022
1
3
4
1022
9
2
1
4
1
3
2
1012
3
1012
4
1
4
4
1
1
2
1
1
3
1
2
2
14
1011
1015
1
2
4
3
4
4
3
3
2
1
4
1
1011
5
9
2
1013
27
1
7
3
3
1
27
1011
3
5
1
1
2
1012
1
11
1
1011
1021
8
26
1
4
1
1
2
1
1
1014
1
4
1012
1011
4
4
2
1
27
4
5
1
1024
1
1013
2
1
1012
24
1
1014
1
4
1


5
15
7
2
1012
1
1
1
2
4
1
1
1012
2
4
1011
1
21
8
7
1014
1013
1
1013
1
1014
2
3
1014
1
3
23
1015
3
6
1023
2
4
1
4
1
25
21
1212
26
1
1013
1
51
2
2
2
1014
4
4
4
1
1
51
7
1
1
1
4
1
9
5
1
1
4
4
2
3
1012
3
1011
2
13
1
1014
3
2
1
3
27
1014
14
4
3
3
4
1
1021
22
3
1
1
7
3
1
4
3
1
4
2
6
1012
1021
1
1015
4
1024
4
1
2
4
6
1
3
1
1014
2
4
1
1
40
3
10
1011
1
2
1014
4
1012
1
1012
25
1
3
1
4
1011
1
1
3
1011
22
3
2
4
2
26
1
2
4
1
2
1022
1012
3
1
48
1
1
4
1
1
1
1
1
1011
2
1014
1
3
1
8
1011
1
1014
1
1011
1
2
14
1
2
6
1021
2
26
1
4
4
1
1013
3
4
1
1011
3
1023
28
26
43
1
1012
2
1
2
1011
3
2
1
4
4
3
6
1012
4
1
1
1
1
3
1
4
1011
1
2
3
1011
2
1011
1013
1
2
1
1
1
1014
5
1023
3
3
1
2
11
4
2
50
1012
5
1
1
4
1
4
3
1
1013
1
4
1
1022
1021
2
7
6
1011
1
1011
1021
1
1024
4
2
1
4
5
5
1
1
2
3
1
1013
5
4
1014
1021
3
2
14
10
1
1
1025
1
4
1
1
6
2
4
1
3
27
2
4
1
2
2
4
1
1
2
4
1
4
4
1
2
3
1
2
7
2
1
49
4
4
27
4
35
1
1023
1
2
1015
1
1
2
1
1
5
3
1012
1
2
1
4
6
49
1011
25
4
1013
1014
8
3
1
2
1
1011
1022
1
1
1011
1012
1011
3
1011
12

1012
2
1014
22
1
1
1
1013
4
5
1011
3
2
1
7
17
4
3
1
1
6
8
1012
3
25
2
2
1014
3
2
2
1
1011
2
8
1
5
2
1
1
1022
1024
4
1013
3
4
1022
1012
3
1014
1024
1011
1013
4
7
1
1021
10
2
25
2
3
4
5
1
4
27
1021
4
1014
1011
2
1022
1015
1
1
1
2
2
1
1
3
1
1012
1011
1
1
1014
1025
4
1011
1
14
4
1
5
1
1
1016
1
1
5
1
3
1012
2
9
2
4
7
7
7
1012
1
27
7
1
3
2
4
4
2
4
1
11
1
1011
39
1
1023
4
1
7
1
2
4
1
8
1012
1
1012
2
3
1
1
4
1022
27
3
3
3
1
4
1
4
1015
1
48
1012
2
10
3
1
2
2
26
2
3
3
2
6
2
1013
3
10
4
1
1011
1
1
1
2
1
41
2
1015
4
4
1
15
5
1014
1
1
1
8
4
1014
9
7
1011
2
26
2
1011
1
3
4
2
1013
4
4
11
2
1
1012
1
1013
4
3
1
3
5
3
1
1012
7
14
1
21
14
5
1
1
4
1
9
2
1
1
1
7
2
4
1
1
3
2
3
1
27
3
1021
1012
2
9
1
1012
3
1
1013
1014
1
4
2
4
1
1011
1
1
1011
1013
1
1
7
4
1
1
1
1
1024
1
3
1014
2
1
1
4
1013
6
1012
7
1013
12
1023
4
7
5
3
2
5
1
7
3
2
1
1
6
5
1
4
2
1
1
4
22
1012
4
1
4
1
2
2
2
1
27
1
4
4
2
4
1013
1
1021
4
4
1013
3
2
1
1
1
1
1013
1012
1021
1
5
5
1
5
1
1
1015
1012
6
1
3
3
1014
1
1011
3
1012
11
1022
5
1022
1
6
1021


3
1021
3
1
8
4
1
1
1
7
1
3
1011
1013
4
4
1012
1011
2
1
3
1
4
2
3
3
2
1012
1
4
1013
5
4
2
6
1
10
6
1
2
2
11
1
1
1013
4
1
1
3
5
1
1014
4
4
1023
1013
2
1
1
2
21
5
1014
1
1
1021
1
1015
2
1
1
7
1012
7
1022
9
2
13
2
5
1
1
2
1021
4
2
2
3
1
14
27
14
1011
1
2
3
3
1
1
2
2
1013
1
1011
1
1
1
12
5
1
4
4
1
1
1
1
3
2
1
1
1011
27
1016
15
2
2
3
2
4
1
2
3
1014
1
2
3
1011
1
3
6
1
1
1
4
1212
7
1
1
1
4
4
3
1015
1012
5
1
6
3
1
2
3
5
2
4
6
10
1011
1014
1
1
1
1013
6
3
1
3
1011
1
1
4
1
1021
1022
4
1
1011
1
1
1
1023
2
1
1014
5
1012
5
4
1
1
2
3
1
2
5
2
1
1
5
1
3
6
2
1
1
12
27
1
2
1013
1
1
3
2
1
39
1023
3
28
27
6
26
2
1
1
1
2
4
12
5
1
5
1
2
1014
1012
1
4
1
1011
1
1
1023
1
2
1
1
1
13
25
1
1012
1
1
1012
1023
1
1011
1
3
1
1
1012
1
3
1013
1
1
1
2
1
1012
2
1011
1
1
1
2
4
2
5
2
4
1
1013
11
3
1011
22
4
1014
22
3
1
1
1
1
4
1011
4
4
5
25
4
1
1
4
1
15
5
1
3
5
7
4
20
2
2
2
1021
1
1011
3
10
3
2
1013
7
1
1
2
4
1
1
4
4
1011
1
21
11
10
2
1012
3
2
1012
27
1012
1
3
1
5
1014
1
3
1
41
5
27
3
1
2
1012
1
1
1012
3
1
1011
1
1
1013
4
2


2
27
1
4
2
1
2
24
1015
1012
4
2
1
1
1
4
5
1
1
1012
1011
4
1013
1022
1023
4
1014
25
1013
3
1011
3
1
1
1
3
1
3
4
1011
1013
1
1
2
1
7
2
1023
3
7
5
3
1015
1
2
2
1
1012
2
1
2
25
5
9
1014
1
1
1
1011
1212
1
3
1
2
2
4
1
1024
1012
1
1
1
1
1
1
24
1
2
6
1
1013
1011
1
3
4
5
6
1014
1013
12
4
1
8
2
11
1
1
1011
1
5
1012
1013
1
1
11
7
1012
4
1
1012
3
1
1011
3
6
1
1
1
1011
5
3
5
2
5
1
1
1
1
1
4
6
2
5
1
12
2
3
4
1
1
4
6
1015
3
2
1013
1
4
5
1014
1014
1
1
1012
2
7
1
3
20
3
1013
1
2
1012
6
1012
1
4
3
4
1013
3
1011
1
1
1
1
17
1011
1
2
1
2
1
1
1013
3
1
7
1012
1015
1
1
4
35
2
4
4
1012
3
2
2
1011
10
3
1011
4
1
1
3
2
1
5
1
2
2
2
1
2
25
1024
1
2
1011
1013
4
5
2
13
1012
1
27
1
1
1014
1
29
1
1212
1013
1
1
1
1
7
2
1
1013
4
2
1014
3
1
1
1
1
7
1
2
12
2
3
1013
1
52
1011
3
1
1
1
1014
1
6
1
1
6
4
1
1
1012
4
2
4
1014
1
1
4
5
1012
3
1
1
1
1
8
2
1
4
1
4
5
27
1
1011
1
1
5
1013
1012
11
1012
3
1014
3
4
5
1013
2
1014
14
2
4
1
1011
2
1013
1212
3
1013
4
2
1013
1012
1013
3
4
2
3
1
1012
4
1
1
12
3
1014
27
1
1022
1
1
1021
3
2
1014


4
18
3
2
1
1
3
2
1
1021
1
1
1
1
1012
2
1
2
3
2
1011
1011
2
1011
3
1
3
1
3
3
4
1
2
4
1014
5
2
4
24
1011
2
2
1
1
3
1
4
1012
3
1012
4
4
1
8
1
5
1
1
2
1012
1
1
1
1013
1
5
3
5
1
1
35
1012
4
4
14
1
14
1021
1
1
17
25
1
1
1
1
1014
4
1
4
1024
23
4
24
5
1011
1
2
1
4
1012
3
1012
1
1013
11
7
3
1
3
3
1
21
7
4
1
3
1014
1
4
1
1013
4
1
1013
1014
1011
4
2
2
1
7
4
1
2
3
2
2
7
1011
2
1014
3
7
3
1
2
2
1
1
1
2
40
1
1
1
5
1
1
1012
3
1
2
1013
2
1012
4
1
1
7
1
1212
5
1011
1021
1014
2
1
2
1014
7
1
3
4
1
5
3
2
2
1011
2
2
1012
2
3
8
2
1
1
4
3
1011
1
2
4
12
4
2
1013
1011
1021
1014
1
3
1
1
6
1
7
2
2
3
3
1025
1
7
3
1
1
22
4
4
2
2
1212
6
1
2
1011
1011
1023
1
4
3
4
2
1011
2
3
2
1011
1
4
1012
1
1012
1
4
2
1
2
1
1
5
1012
2
1
1
2
1
1014
1
1
3
1023
1212
1
3
1013
2
1
2
2
1
4
1012
1
1014
1
2
1011
1011
4
1212
3
10
1014
1
4
1
1
1013
21
1014
6
1011
9
1
2
1011
1
1013
15
1011
4
3
1
1014
1022
1011
2
1013
1013
4
1012
4
1
5
1
3
2
3
1
11
1
1
1013
2
3
3
8
1212
1
1
1
1014
26
1021
1014
7
3
4
3
1
13
6
2
1012
1011
14
1012
1
1021
4
7
102

2
1
4
1
2
1014
5
2
4
8
2
1
5
4
1014
5
1
2
1
1013
1022
2
1
3
7
3
5
1
3
4
2
1014
1014
2
1012
3
1013
1
4
2
2
4
1
2
2
1
27
1013
1
1
2
1
3
1
27
9
1
1
1
3
2
4
1
1
2
1011
1011
2
12
5
1
4
3
1
1
25
1
1
35
1
28
2
1
1
4
5
1
2
1
1
1
1
1
2
1
15
2
1
2
1011
1
1
27
3
4
1014
1
1014
4
1013
2
3
1021
1014
2
1011
1011
1
1
4
37
4
1012
1
1011
1011
9
1023
1012
2
4
1
5
2
1
1
4
2
2
4
1011
1012
1
10
1
1011
3
1
1
1
3
1
3
6
3
4
1
1
4
1022
1
8
7
4
1013
2
1
1011
1
27
1015
6
7
3
4
1011
2
13
7
4
1
1
1015
1012
1013
1011
2
1012
1
27
4
1
1013
27
1012
1
3
3
4
1012
3
2
6
6
1
4
1
1
3
4
1
4
4
1012
11
1011
1
2
3
1
2
1014
2
1
3
11
1
1
6
1022
1
5
1013
4
1
1
3
1
1
1
4
43
1
2
7
1011
4
25
4
1013
1
4
1014
3
1
1
2
1
2
1
1023
1
1
1
3
1
1014
2
3
1
3
4
1
1
2
1
1
5
6
1
6
1
1021
2
11
1
1
3
1
2
1011
1015
3
9
1
4
4
2
1012
4
3
2
19
1
1
4
4
1011
2
1012
7
1
1
4
2
1
2
5
1
1023
2
43
1
6
2
1022
1011
1
1012
1016
3
4
4
1
4
21
2
4
1013
1014
3
1
1022
3
27
1
1
1
1
1
5
1013
1
1
1012
1
4
4
4
1
1023
2
1
1011
1
2
1013
2
2
1011
1022
4
33
1
2
3
3
1
1
1
4
1

1
1
4
4
2
1012
3
1
1
1012
1
1
21
1
1
1
1
3
1
3
1011
1
4
1011
1011
1
1
1
3
4
2
2
1
7
7
1
2
1
4
3
31
4
1011
1013
6
3
2
1
3
1
1012
1
6
1022
1
3
1
2
1021
8
3
1
1
1012
27
3
1011
1
2
2
4
1
2
4
3
1
1
2
5
1
4
1011
2
3
1024
3
1011
1
1
3
1012
1
4
2
27
1023
1011
2
1
5
1
2
1
4
1
4
1
48
3
1011
10
1013
1
1
2
1013
1
1011
2
1
4
3
1
4
4
1011
8
1
34
3
1
1
2
1
9
7
21
2
3
4
20
1014
1
4
7
2
1023
7
3
3
2
3
5
45
1011
1
3
1
1
6
2
1
1
14
1
4
1012
4
1013
1
1023
1
1
4
1
1
1013
1
1021
5
1014
6
4
1
2
1011
1022
2
4
3
2
2
1021
1
1
1
11
1021
1011
1
1014
3
1
5
1
1
1011
1
1
1
3
9
3
1012
16
2
1023
4
1
5
15
1
2
1014
4
4
4
1
4
2
5
1
2
3
1
1
4
12
3
1011
1
1
1
1
3
1011
2
23
1022
1
1
5
5
1
3
2
1021
3
7
1
22
1022
1
1
1
1
1
1
3
7
1
4
1
1
1014
13
1011
3
1
2
7
1
1
2
2
1
1
2
1
1
1
2
3
1011
5
1021
2
1
2
1
1021
6
4
3
4
1
1
1
4
1011
4
1
3
1
1
1011
3
6
1016
3
2
3
5
1021
4
4
3
1
2
1
1
4
4
4
6
5
1
5
1
5
7
6
1021
2
2
1014
1013
1014
1
1
4
1
1
2
2
1012
1
1
1
2
7
2
1
1011
5
1013
1012
1
2
1014
2
1012
2
1
1
1
2
3
4
59
1
1013
4
4
3
5
5
2
1
21

2
3
1
2
4
1
1
3
14
1
1021
1
1011
1
2
1
2
14
5
5
1
1
1
1024
4
1023
2
1
2
2
4
13
4
5
1
1
5
1014
1
2
2
4
1
1011
4
4
3
1
1
27
1
3
3
3
4
1
1012
1
4
1013
1013
1
4
1011
1
3
1
2
7
1022
2
1
6
2
4
1
2
3
2
4
3
1
3
1
1
1
1011
1
1
4
1
6
2
1
1021
1
2
1025
1
3
33
2
5
1
1
1022
25
12
1
4
1013
3
4
2
1
1
25
1
2
26
1
1
4
2
5
1011
1012
1
4
1
1011
1023
1012
1011
1
1
1011
3
1023
1011
1
2
1014
3
1
2
1012
1011
2
1011
2
1
1011
1
1013
39
4
2
1011
2
1
5
1
1012
1012
4
2
2
4
3
1
1
1023
3
1
3
2
4
2
2
1
1014
3
1021
37
2
3
1
1013
69
1011
2
1011
2
1011
1011
1
1
1011
1
2
2
1
2
5
2
5
4
4
1
3
2
1
5
3
1
1
1
1
9
1012
1
3
1022
1
1
4
3
4
4
36
1
2
4
1
1
1011
1
1
1011
1
11
1021
1
27
21
1011
4
4
1
1
22
1
6
27
3
2
2
5
2
22
8
1012
9
1023
3
3
4
1
2
5
1023
2
1011
4
3
2
1212
3
1
3
1012
1
1
1
7
15
3
1
3
4
1024
1
1013
1013
1
1
1
1
1
1012
1
1014
4
1014
26
3
3
4
1012
7
1
1012
28
16
25
10
2
4
3
3
2
1
3
3
1023
2
1022
5
4
1
1
2
1
1
7
2
1
2
27
2
2
2
1
4
1011
17
5
2
2
1
1
2
2
1
3
27
1
1
1
3
4
1
35
2
16
1
13
1
3
1014
1
2
1
2
1
14
5
18
5
6
5
1


4
1
1
48
1013
2
2
39
1
1
1012
1014
4
1
4
1
23
2
1
3
1
4
1012
2
6
1013
1015
1
2
2
2
1
2
4
1
1011
7
4
1
1
4
1023
1
1
2
1
4
1012
1
1025
1
23
4
1
1011
1
4
39
1013
1
2
24
31
1011
1
1
27
1
2
4
1
3
1
3
1014
4
1
24
5
2
2
3
1
1022
1014
2
4
4
4
3
1
9
39
8
1011
5
1012
4
1011
2
1
7
1
1025
13
1
1013
2
1011
1014
75
1
1
3
1012
1012
1014
1
1011
1
6
1
8
1
1
2
4
2
1013
4
4
4
2
1
1
3
2
1012
3
8
1
1
3
3
1013
1
1012
1
3
1012
2
1012
8
1021
2
2
17
3
3
1011
2
17
2
1015
1025
1013
2
3
4
1
1
5
1012
1
1012
5
50
2
1
27
1
12
1
21
1
4
1013
1011
3
1011
1
1013
1012
2
1
2
1
1
3
2
1012
3
1024
1
1
3
1
1
4
1
1022
2
2
43
1
1
1
1
1022
4
4
1011
1
1012
1
27
1012
2
2
48
2
1
1
2
1
2
1021
1
1
2
1
1
3
2
1
1
1
2
1011
1022
1
4
4
4
7
2
2
2
1
2
4
1022
1
3
1
1013
4
1
2
1011
1
2
1
4
4
1
1
1
2
1011
5
1
1
5
1011
2
4
3
1
1
1013
3
1
1016
1
4
4
25
4
25
1012
2
1
1
1
2
1
7
1021
4
1011
1
1
21
1012
1
1
7
5
1011
1012
5
2
4
3
5
2
21
1
2
10
1
1
5
1
2
3
1
2
1
9
1011
1011
2
1
1
1
5
1022
1
2
1011
6
1
2
1
27
1
1013
2
1012
2
3
1023
1
5
1013
4
4
1
1024


1
1013
3
3
1
1
3
2
1
10
1
4
1
1021
6
2
1
11
4
4
1
3
4
2
1
3
4
1
1
4
1
1
2
2
9
1
1
3
1
1
1013
3
25
1
1012
1
1
26
1
1
1011
27
1
1011
1012
4
43
3
1012
4
1
12
4
2
1011
7
2
1
2
1
2
1
7
5
1012
1
1
1
1
1011
2
2
1
1
1
1
4
2
1
4
1
5
4
1
1011
2
2
2
2
1
1012
2
2
1
2
1
2
3
3
1
1
1
6
3
1
7
5
1
1
3
1
2
1
1
1013
2
2
4
1
3
48
1
1
1
2
1014
1012
3
4
1
5
27
3
1011
1011
1
11
1
1
1
4
1013
4
9
1011
1011
3
1023
2
1
25
3
1011
1011
1
5
1
2
7
2
4
3
1012
5
1
1
2
1
2
2
1
1
4
1
1011
1
4
1
2
1013
3
5
3
4
7
3
1
1
6
1014
1
2
3
1013
2
2
3
1
1
2
1
1
4
1
1023
4
3
1023
4
1
23
12
1012
2
2
2
4
1
1012
19
1012
2
1011
1
3
1
1
2
1024
4
4
3
3
2
1
4
3
2
1
1012
1014
4
1015
2
4
1013
2
3
1
15
1
1
1016
1012
1
3
2
8
1
12
1
2
3
1
1011
1
4
1012
4
1022
5
2
1
4
4
1
15
2
1
1
1
8
1024
2
4
2
1021
1012
3
2
1
1012
1023
1
15
2
1
4
1012
1
4
1011
1
1013
6
2
1
1
4
16
1024
4
1
2
1013
1011
1
3
1
2
21
5
1
4
1012
1022
2
3
1
1014
1
1
27
1
13
5
4
2
4
2
4
1
4
1012
1
1013
1
1
3
26
5
1
4
1014
2
1014
4
3
8
1
1
6
7
4
2
1
1012
1011
1013
1
1011
4
3
1
1
27
8
1

11
1
1
2
2
1
4
1
1
1013
4
1
2
1
1
1013
1
2
4
1
1014
2
3
4
3
1
12
1021
1
2
1
1011
1011
1
4
1
1011
2
3
7
3
1011
1014
1
2
50
3
27
1013
5
1
14
2
3
1
4
1
4
3
4
5
1012
1
4
1
4
4
3
3
1011
10
4
3
2
1
2
1
7
2
1
1
27
11
1021
3
3
10
4
2
5
4
1012
1013
1
5
7
1
4
1021
5
4
3
1
1
4
1
1
1022
4
4
1
1
1012
1
1015
1015
1
1
1
4
1012
1
2
1021
1011
3
3
1
1012
13
1011
3
3
6
1
3
1023
1012
1
21
1
2
4
8
12
4
1
5
27
2
1
1
1
1011
1014
2
4
1
1
1012
1
27
1011
1014
1012
1
3
1
1
1011
2
6
2
7
1
4
5
2
14
14
1
2
1014
1
1021
2
5
1
2
1
3
1
1
2
1021
1012
1
4
1
4
1
2
1013
3
1
2
1
2
4
5
4
1
1
3
7
3
1
1
3
1012
2
1
2
3
1
5
2
1
21
25
2
7
2
1012
1
1
4
1
1
23
2
1
1
1
2
2
1
2
2
1
44
22
1
2
1
27
6
1012
1
3
1
1012
1
1
15
1
1012
3
2
2
2
1
1
21
4
4
4
2
4
1
32
1
3
1
3
5
1011
4
1
5
1012
2
1
1013
3
1
1
1011
22
3
3
5
4
4
1
1
1023
1
1
4
1
1
1
1
1
1
23
1
6
1013
1
3
1
7
1
1
3
1
4
5
3
1
4
8
4
4
1
2
3
1
1
1011
2
1011
1
1
3
1
11
21
2
1012
1
3
1
1012
13
1
1013
3
1014
4
1
1023
1
1
4
2
1
1212
4
1
1012
2
1
25
1
1
1021
26
4
2
2
1011
4
5
1
1011
36
2
2

1
1
4
5
2
1012
1
1021
2
1
3
2
1011
3
27
7
5
1021
3
1011
1
1012
4
1
1
1012
3
1011
2
1011
8
1011
1011
1013
2
2
6
4
1
2
2
1012
2
1
24
1012
1023
3
6
5
2
10
1014
1012
1
2
1012
4
1012
1
4
27
1
1
5
3
2
1
2
1
1
2
3
3
14
4
1
21
3
1
8
3
1
1
1011
1
1
5
1011
3
7
1011
1012
1
22
3
1
3
1021
2
4
1
1021
1
1014
27
26
1011
1
1
1021
1
1
22
5
2
1022
1022
3
3
1
4
4
1024
26
25
1012
6
1
2
5
1
1011
1
3
1
3
2
2
1
4
3
14
3
3
4
1013
5
1
2
4
1
2
3
3
1
1
1
2
2
2
4
1
5
4
1022
1
1011
2
1
4
21
3
1
4
4
24
3
3
2
1
1
2
1022
4
1023
2
1012
1011
2
8
2
1
1
4
1
1
1
3
1
5
1
1
1023
1011
1
2
1013
4
2
1
4
2
3
2
3
1013
1012
1
1
2
1011
1
1
1022
1
4
4
1
1014
29
1
3
21
3
1
26
8
2
1
1013
1011
4
2
1
3
3
1013
1014
15
1021
4
3
1
4
4
2
1
1012
3
1
3
21
3
1012
2
3
1012
1012
1
1
1
1
4
4
1
1
1012
27
1
5
1
1013
2
1
2
3
8
6
3
2
1
3
2
1
1
36
2
1
1015
1011
1012
1
1024
1013
1
1022
1
1
4
1023
4
6
1
1
21
2
1012
2
2
13
1
4
2
4
2
3
1014
1022
2
3
2
4
3
1
5
4
3
1
1
1
4
2
4
1012
1
1
1
5
1
1011
1
14
1
1
2
1011
7
2
5
1
1
1021
1
1
4
5
1
1
1013
3
1014
1
3
1


1013
3
2
2
1014
1
1012
1
2
4
1011
2
27
1
2
1012
2
5
1
1011
1
4
3
3
4
3
1
2
4
1011
1
1011
27
1
1
1021
2
1012
1
13
2
1
2
1
4
1011
2
5
1
2
7
1
1014
2
2
4
1
2
4
2
4
4
2
4
3
1012
5
1
1
1013
1
1014
7
1011
1
2
22
1
1012
1
1
5
7
2
1
1011
4
3
3
4
1011
1
11
1011
3
5
1
1
5
4
6
1
3
3
7
4
1011
1015
2
1
17
1
15
1021
3
4
5
1
2
3
1014
27
1013
27
1012
1
3
1
6
4
7
9
2
1011
1
4
1013
7
2
50
1
2
2
1014
6
1
7
7
1
3
1012
1
1
2
1012
2
1012
1
14
5
2
1
2
1
1
1
1
2
1012
25
2
2
1
9
1015
3
1
1
5
6
2
4
1
2
2
2
1
2
3
2
1
3
1
1022
6
2
1
3
4
3
4
3
3
4
2
1
7
5
1
2
1
1
1
8
3
2
4
1
4
4
1
4
3
24
2
1011
14
4
1
5
1012
1
1
4
5
3
9
2
1011
4
4
7
6
1013
4
3
4
1
27
38
14
1
3
4
1
1
2
1
4
4
5
5
2
1022
1
27
4
5
1
4
4
1
1015
1
1
2
1
1013
3
1014
4
1022
2
1
8
14
1
1
4
4
3
12
4
1
1023
1014
1011
21
4
2
3
3
35
1011
2
1
4
4
1
2
2
1
1
2
3
4
5
1
1
1
2
4
1011
1
2
2
8
1
3
1
2
1011
52
4
1
1014
2
1
1014
12
1
1
2
2
4
4
2
2
1014
3
1
1011
3
1011
1013
1
4
5
2
1012
1012
1011
3
1013
2
12
1
1012
5
1013
2
1
1
3
1
3
1
1
5
3
21
3
1
1
1013
1
1012
1013
1
4

1
4
4
1011
1012
3
1
1012
1014
1023
3
2
3
27
4
2
27
3
2
2
1014
1
2
1013
4
1
4
2
1
4
14
1013
1
1
1
1
1
1015
5
3
2
1
5
4
4
15
2
3
3
3
1
8
3
23
3
1
1
1
1
10
3
7
1
1
1
1
1
3
1
1
1
16
3
2
1023
7
2
4
4
2
1
2
1
8
1011
4
3
2
1
1
1
4
8
1
1
1
1
3
1
1
1011
26
1015
1
2
2
1014
2
4
5
4
1014
1021
1014
4
1013
6
4
4
1
5
4
1022
1
1
4
1021
3
1212
1
1013
2
1022
2
3
1016
5
1
2
1011
1
1013
1
2
1
26
7
6
39
1
1021
1011
3
1
1
2
3
16
1022
2
1
2
1
1
1015
1023
5
12
2
2
1
1016
2
1021
1
1
1
1
1
3
3
1011
2
2
1
3
22
2
1012
2
1
1
1011
1
1
4
1012
1
7
38
2
1022
6
4
1011
4
1013
1
4
3
1012
2
2
3
2
1012
6
1
5
1
2
3
3
47
1013
1
11
1
2
2
1
1
1
1013
6
1
4
1
3
1
6
1011
1
2
1
2
1
1
2
3
1
1
1012
2
1
4
2
1
1
28
1
2
1
1011
1011
2
1012
1
1
2
1012
1
9
1
1013
4
3
1
2
1
1012
1
1
1013
1021
4
1
1
1
1
3
4
1014
12
1
1013
1012
1014
14
1
4
1
3
2
1014
1
1
1
25
1021
2
2
2
4
1
2
1
26
5
2
1
4
1011
1015
15
16
3
1012
1022
1
4
6
5
1014
3
2
5
1013
1
27
4
2
1
1
1212
35
1011
2
1022
1012
1
2
1
1
7
1
1
2
1
2
1
3
4
4
4
4
5
1011
1013
11
6
24
2
1
27
4
1012

1012
9
8
8
1014
1
5
8
3
21
26
1
1013
1
12
4
4
4
1013
1011
4
1011
4
3
1013
2
4
3
1
1016
23
1
22
5
1
2
1012
2
5
1
1
5
1023
1212
1022
2
1013
1013
2
3
1
3
1023
2
1011
1
1
17
1023
1011
2
3
35
8
2
1
1014
1
3
1012
4
2
1
1
1
1
1012
1011
4
1012
1014
1011
1
1
27
5
4
2
2
2
4
1
3
1011
2
2
4
4
5
4
1
26
2
4
2
2
1
3
1
2
1014
1
1022
1
3
5
2
1
1011
1012
1
5
1
2
27
4
3
1
2
2
1022
24
1
2
27
1013
1
2
1
1011
6
2
3
1
1013
1012
1
1011
4
2
3
1013
1013
5
1
3
1
1
1
1021
3
5
1
1022
2
5
3
3
2
5
3
1
2
2
3
1014
1
3
4
1
3
7
1
1
1
1
1
1014
4
4
4
2
2
3
1
4
3
2
3
1
1
27
5
7
3
1
4
1
27
1
1
4
2
1
4
1012
1011
4
1022
4
1
1
1022
5
3
1011
2
2
3
4
2
1011
1
1014
1011
5
4
2
5
2
3
21
1012
4
2
3
1014
3
1023
3
1
1022
1
1
3
4
2
4
4
16
3
1011
1
3
4
3
4
3
4
1
4
27
4
2
4
4
2
4
1014
1
2
2
1
3
1012
2
5
1
1
1
1
8
3
1
2
1022
1
1
1
4
25
3
3
1024
3
4
1
5
6
1
1
3
2
1
27
3
2
1014
4
4
2
1
2
3
1
4
4
1
2
4
1012
3
1
4
1
4
15
8
2
1012
1013
1
2
2
1
6
1012
10
2
3
3
1
3
1
6
1
4
1
1014
2
4
2
4
2
1
2
4
1014
5
2
1
3
2
1212
1
1
1012
2
1
1
1
2
1013
1
35
1

4
2
4
1
1
1
1011
3
4
1023
1021
1
4
1
1012
2
3
1011
1
25
7
3
1015
4
1
1023
1
1
7
1
1
1014
1021
4
2
3
1
1
5
1015
5
1
1011
6
10
4
2
1
4
2
7
1
2
3
3
1022
1
3
2
18
1011
1
1022
3
20
1
8
2
1
1
1012
1014
1
3
2
1015
1
1
1
1
25
13
2
1
12
1
5
2
4
1
1014
4
2
1013
2
5
1
1012
1
3
4
2
1022
11
4
26
3
1021
1024
1
1
1
4
1
4
3
1
3
3
1
1
1
2
7
9
16
7
1
1
9
2
2
1
36
19
7
1
2
1012
3
1
1021
2
13
1
1
1011
1014
1015
2
2
2
21
2
1
1012
1011
2
1014
1
1
2
3
1
1
10
3
4
1014
1
1011
3
2
1011
1
1
1
4
1012
2
14
1021
2
1
1011
1
1
1
1
1013
3
2
7
19
22
1014
1
1
1
4
8
1
1022
1
2
1024
4
1
1
12
1
8
4
6
2
2
2
7
1014
1
1
1012
3
1011
1
2
3
1
2
1
4
1011
1
4
3
1
1
1021
1013
1
7
4
2
3
5
1
3
2
1
2
1
4
4
2
2
7
1014
8
3
1011
1
3
2
3
1
1
4
1
2
1
3
1
5
13
4
27
1012
4
3
3
4
1012
6
1
2
11
1013
3
1013
3
1011
1011
4
4
52
3
2
4
25
1011
4
3
2
1
8
8
1022
4
1015
5
27
5
3
4
1012
2
1011
3
4
1012
1021
2
1
2
3
1014
1
1013
3
1
4
5
26
1012
1
4
5
7
14
4
1011
1
8
3
3
1
1
4
4
1
1
3
3
1
2
2
4
1
5
26
1
1
1014
1015
5
13
5
3
3
4
1
1
3
4
1
2
4
1
2
1011
4
1


In [4]:
niveis

['FDO1',
 'FCA3',
 'FDO1',
 'FDJ1',
 'FDE2',
 'FCA4',
 'FDE2',
 'FCA4',
 'FDE2',
 'FDO1',
 'FDO1',
 'FCA3',
 'FDO1',
 'FST2',
 'FDO1',
 'FST2',
 'FDO1',
 'FDE2',
 'FCA4',
 'FDE2',
 'FCA3',
 'FCA4',
 'FDO1',
 'FCA3',
 'FCA2',
 'FDO1',
 'FDO1',
 'FCA4',
 'FDT1',
 'FCA2',
 'FDO1',
 'FCA3',
 'FCA4',
 'FDT1',
 'FDO1',
 'FDT1',
 'FDO1',
 'FDO1',
 'FCA4',
 'FDO1',
 'FDO1',
 'FDT1',
 'FCA4',
 'FDT1',
 'FST2',
 'FCA4',
 'FDT1',
 'FDO1',
 'FDO1',
 'FDO1',
 'FDO1',
 'FDE2',
 'FDO1',
 'FDE2',
 'FDT1',
 'FCA3',
 'FDT1',
 'FDO1',
 'FDO1',
 'FST2',
 'FDO1',
 'FDT1',
 'FDT1',
 'FDO1',
 'FDO1',
 'FCA4',
 'FDO1',
 'FCA2',
 'FST2',
 'FDT1',
 'FDO1',
 'FDO1',
 'FDE2',
 'FDO1',
 'FDO1',
 'FCA2',
 'FDO1',
 'FDE2',
 'FCA4',
 'FDO1',
 'FST2',
 'FST1',
 'FDT1',
 'FDO1',
 'FDO1',
 'FCA3',
 'FDO1',
 'FDO1',
 'FDO1',
 'FDT1',
 'FDE1',
 'FDO1',
 'FDE2',
 'FDO1',
 'FCA3',
 'FDT1',
 'FDO1',
 'FDO1',
 'FDO1',
 'FCA4',
 'FDT1',
 'FDO1',
 'FDO1',
 'FCA4',
 'FST2',
 'FDO1',
 'FDO1',
 'FST2',
 'FDT1',
 'FDO1',
 'FCA3',
 

In [6]:
csv.NIVEL_CARGO

0           NaN
1           NaN
2           NaN
3           NaN
4           6.0
5         604.0
6         602.0
7           NaN
8           NaN
9           NaN
10          NaN
11          NaN
12        101.0
13          NaN
14          NaN
15        402.0
16          NaN
17          NaN
18          NaN
19        304.0
20          NaN
21          NaN
22         10.0
23          NaN
24          NaN
25          NaN
26          NaN
27          NaN
28          NaN
29          NaN
          ...  
805704      1.0
805705      NaN
805706      NaN
805707    501.0
805708      1.0
805709      NaN
805710      NaN
805711      NaN
805712    404.0
805713      NaN
805714      NaN
805715      NaN
805716      NaN
805717      NaN
805718      NaN
805719    501.0
805720    501.0
805721      NaN
805722    101.0
805723      NaN
805724      NaN
805725      NaN
805726      1.0
805727      NaN
805728    401.0
805729      NaN
805730      NaN
805731      NaN
805732    101.0
805733      NaN
Name: NIVEL_CARGO, dtype

In [3]:
csv.columns
        

Index(['Id_SERVIDOR_PORTAL', 'NOME', 'CPF', 'MATRICULA', 'DESCRICAO_CARGO',
       'CLASSE_CARGO', 'REFERENCIA_CARGO', 'PADRAO_CARGO', 'NIVEL_CARGO',
       'SIGLA_FUNCAO', 'NIVEL_FUNCAO', 'FUNCAO', 'CODIGO_ATIVIDADE',
       'ATIVIDADE', 'OPCAO_PARCIAL', 'COD_UORG_LOTACAO', 'UORG_LOTACAO',
       'COD_ORG_LOTACAO', 'ORG_LOTACAO', 'COD_ORGSUP_LOTACAO',
       'ORGSUP_LOTACAO', 'COD_UORG_EXERCICIO', 'UORG_EXERCICIO',
       'COD_ORG_EXERCICIO', 'ORG_EXERCICIO', 'COD_ORGSUP_EXERCICIO',
       'ORGSUP_EXERCICIO', 'TIPO_VINCULO', 'SITUACAO_VINCULO',
       'DATA_INICIO_AFASTAMENTO', 'DATA_TERMINO_AFASTAMENTO',
       'REGIME_JURIDICO', 'JORNADA_DE_TRABALHO', 'DATA_INGRESSO_CARGOFUNCAO',
       'DATA_NOMEACAO_CARGOFUNCAO', 'DATA_INGRESSO_ORGAO',
       'DOCUMENTO_INGRESSO_SERVICOPUBLICO',
       'DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO', 'DIPLOMA_INGRESSO_CARGOFUNCAO',
       'DIPLOMA_INGRESSO_ORGAO', 'DIPLOMA_INGRESSO_SERVICOPUBLICO',
       'UF_EXERCICIO'],
      dtype='object')

In [17]:
for c in csv.values:
    if c[15] == 26270000000607:
        print(str(c[15])+","+str(c[16]))

26270000000607.0,SECRETARIO DA ESCOLA DE ENFERMAGEM
26270000000607.0,SECRETARIO DA ESCOLA DE ENFERMAGEM


## Verificações Entre o CSV e o DW

### Roteiro de Verificações

* Verificar as quantidades das tabelas de dimensão;
* Verificar as quantidades das tabelas de fatos;


In [27]:
#Todos as remunerações de 2016
for d in os.listdir('../datas/2016/'):
    for c in os.listdir('../datas/2016/'+d):
        if '_Remuneracao.csv' in c:
            print(c)
            crg = pd.read_csv('../datas/2016/'+d+'/'+c,encoding='iso-8859-1',delimiter='\t')
            valor = 0.0
            for i in crg['REMUNERAÇÃO BÁSICA BRUTA (R$)'].tolist():
                valor += (float(i.replace(',','.')))
            print(str(valor))
            

20160331_Remuneracao.csv
4895593938.910968
20160131_Remuneracao.csv
4885644600.721209
20160731_Remuneracao.csv
4905128902.201236
20160430_Remuneracao.csv
4898010214.341024
20160831_Remuneracao.csv
5155378984.40498
20161130_Remuneracao.csv
5188558828.176077
20160531_Remuneracao.csv
4899393616.880937
20160229_Remuneracao.csv
4891280683.431067
20161031_Remuneracao.csv
5173554907.675881
20161231_Remuneracao.csv
5197420128.225302
20160630_Remuneracao.csv
4902063422.501156
20160930_Remuneracao.csv
5169410410.895016


In [ ]:
20160131_Remuneracao.csv : 4885644600.721209
20160229_Remuneracao.csv : 4891280683.431067    
20160331_Remuneracao.csv : 4895593938.910968
20160430_Remuneracao.csv : 4898010214.341024
20160531_Remuneracao.csv : 4899393616.880937    
20160630_Remuneracao.csv : 4902063422.501156
20160731_Remuneracao.csv : 4905128902.201236
20160831_Remuneracao.csv : 5155378984.40498
20160930_Remuneracao.csv : 5169410410.895016
20161031_Remuneracao.csv : 5173554907.675881
20161130_Remuneracao.csv : 5188558828.176077
20161231_Remuneracao.csv : 5197420128.225302

In [34]:
#Todos as remunerações de 2017
for d in os.listdir('../datas/formatação/2017/'):
    for c in os.listdir('../datas/formatação/2017/'+d):
        if '_Remuneracao.csv' in c:
            print(c)
            crg = pd.read_csv('../datas/formatação/2017/'+d+'/'+c,encoding='iso-8859-1',delimiter='#')
            valor = 0.0
            for i in crg['REMUNERAÇÃO BÁSICA BRUTA (R$)'].tolist():
                valor += (float(i.replace(',','.')))
            print(str(valor))

20170131_Remuneracao.csv
5679818385.099183
20170831_Remuneracao.csv
5605475510.412323
20170731_Remuneracao.csv
5566600421.249846
20170430_Remuneracao.csv
5598773228.88935
20170331_Remuneracao.csv
5599518037.229515
20170930_Remuneracao.csv
5527065569.212528
20170531_Remuneracao.csv
5584709526.749502
20170630_Remuneracao.csv
5573682130.769721
20170228_Remuneracao.csv
5603389426.949312


In [ ]:
20170131_Remuneracao.csv : 5679818385.099183
20170228_Remuneracao.csv : 5603389426.949312
20170331_Remuneracao.csv : 5599518037.229515
20170430_Remuneracao.csv : 5598773228.88935
20170531_Remuneracao.csv : 5584709526.749502
20170630_Remuneracao.csv : 5573682130.769721
20170731_Remuneracao.csv : 5566600421.249846    
20170831_Remuneracao.csv : 5605475510.412323
20170930_Remuneracao.csv : 5527065569.212528

 **Atenção:** Mês 3 de 2017 na tabela fato_remuneração está errada, CSV=5599518037.229515 e DW=4054527427.37

### Verificando fato_sem_cargo_funcao_vinculo

In [4]:
crg = pd.read_csv('../datas/formatação/2017/201701_Servidores/20170131_Cadastro.csv',encoding='iso-8859-1',delimiter='#')

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,12,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [19]:
#np.isnan(crg.DESCRICAO_CARGO.tolist()[0])
i = 0
for c in crg.columns:
    print (str(i)+":"+c)
    i+=1

0:Id_SERVIDOR_PORTAL
1:NOME
2:CPF
3:MATRICULA
4:DESCRICAO_CARGO
5:CLASSE_CARGO
6:REFERENCIA_CARGO
7:PADRAO_CARGO
8:NIVEL_CARGO
9:SIGLA_FUNCAO
10:NIVEL_FUNCAO
11:FUNCAO
12:CODIGO_ATIVIDADE
13:ATIVIDADE
14:OPCAO_PARCIAL
15:COD_UORG_LOTACAO
16:UORG_LOTACAO
17:COD_ORG_LOTACAO
18:ORG_LOTACAO
19:COD_ORGSUP_LOTACAO
20:ORGSUP_LOTACAO
21:COD_UORG_EXERCICIO
22:UORG_EXERCICIO
23:COD_ORG_EXERCICIO
24:ORG_EXERCICIO
25:COD_ORGSUP_EXERCICIO
26:ORGSUP_EXERCICIO
27:TIPO_VINCULO
28:SITUACAO_VINCULO
29:DATA_INICIO_AFASTAMENTO
30:DATA_TERMINO_AFASTAMENTO
31:REGIME_JURIDICO
32:JORNADA_DE_TRABALHO
33:DATA_INGRESSO_CARGOFUNCAO
34:DATA_NOMEACAO_CARGOFUNCAO
35:DATA_INGRESSO_ORGAO
36:DOCUMENTO_INGRESSO_SERVICOPUBLICO
37:DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO
38:DIPLOMA_INGRESSO_CARGOFUNCAO
39:DIPLOMA_INGRESSO_ORGAO
40:DIPLOMA_INGRESSO_SERVICOPUBLICO
41:UF_EXERCICIO


In [27]:
#VERIFICANDO TODOS OS MESES DE 2016
#crg.DESCRICAO_CARGO [4]
#crg.FUNCAO [11]
#crg.SITUACAO_VINCULO [28]
#Todos as remunerações de 2016
for d in os.listdir('../datas/2016/'):
    for c in os.listdir('../datas/2016/'+d):
        if '_Cadastro' in c:
            crg = pd.read_csv('../datas/2016/'+d+'/'+c,encoding='iso-8859-1',delimiter='\t')            
            for v in crg.values:
                if pd.isnull(v[4]) == True and pd.isnull(v[11]) == True and pd.isnull(v[28]) == True:
                    print(v)

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


**Confirmação:** O ano de 2016 não possui servidores que não tenham vinculo, nem cargo e nem função

In [37]:
#VERIFICANDO TODOS OS MESES DE 2017
for d in os.listdir('../datas/formatação/2017/'):
    for c in os.listdir('../datas/formatação/2017/'+d):
        if '_Cadastro.csv' in c:
            crg = pd.read_csv('../datas/formatação/2017/'+d+'/'+c,encoding='iso-8859-1',delimiter='#')
            for v in crg.values:
                if pd.isnull(v[4]) == True and pd.isnull(v[11]) == True and pd.isnull(v[28]) == True:
                    print(v)

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,12,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


**Confirmação**: O ano de 2017 não possui servidores que não tenham vinculo, nem cargo e nem função

In [3]:
CARGOS_DISTINTOS = []
FUNCOES_DISTINTAS = []
VINCULOS_DISTINTOS = []

In [19]:
#VERIFICANDOS OS CARGOS de 2016
for d in os.listdir('../datas/2016/'):
    for c in os.listdir('../datas/2016/'+d):
        if '_Cadastro' in c:
            crg = pd.read_csv('../datas/2016/'+d+'/'+c,encoding='iso-8859-1',delimiter='\t')            
            for v in crg.values:
                #Cargo
                if v[4] not in CARGOS_DISTINTOS:
                    CARGOS_DISTINTOS.append(v[4])

                    
for d in os.listdir('../datas/formatação/2017/'):
    for c in os.listdir('../datas/formatação/2017/'+d):
        if '_Cadastro.csv' in c:
            crg = pd.read_csv('../datas/formatação/2017/'+d+'/'+c,encoding='iso-8859-1',delimiter='#')
            for v in crg.values:
                #Cargo
                if v[4] not in CARGOS_DISTINTOS:
                    CARGOS_DISTINTOS.append(v[4])

print(str(len(CARGOS_DISTINTOS)))

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,12,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


2348


In [20]:
#VERIFICANDOS OS FUNÇÕES de 2016
for d in os.listdir('../datas/2016/'):
    for c in os.listdir('../datas/2016/'+d):
        if '_Cadastro' in c:
            crg = pd.read_csv('../datas/2016/'+d+'/'+c,encoding='iso-8859-1',delimiter='\t')            
            for v in crg.values:
                #Função
                if v[11] not in FUNCOES_DISTINTAS:
                    FUNCOES_DISTINTAS.append(v[11])

                    
for d in os.listdir('../datas/formatação/2017/'):
    for c in os.listdir('../datas/formatação/2017/'+d):
        if '_Cadastro.csv' in c:
            crg = pd.read_csv('../datas/formatação/2017/'+d+'/'+c,encoding='iso-8859-1',delimiter='#')
            for v in crg.values:
                #Função
                if v[11] not in FUNCOES_DISTINTAS:
                    FUNCOES_DISTINTAS.append(v[11])

print(str(len(FUNCOES_DISTINTAS)))

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,12,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


52


In [4]:
#VERIFICANDOS OS VINCULOS DISTINTOS de 2016
for d in os.listdir('../datas/2016/'):
    for c in os.listdir('../datas/2016/'+d):
        if '_Cadastro' in c:
            crg = pd.read_csv('../datas/2016/'+d+'/'+c,encoding='iso-8859-1',delimiter='\t')            
            for v in crg.values:
                #Vinculo
                if str(v[27])+'_'+v[28] not in VINCULOS_DISTINTOS:
                    VINCULOS_DISTINTOS.append(v[28])

                    
for d in os.listdir('../datas/formatação/2017/'):
    for c in os.listdir('../datas/formatação/2017/'+d):
        if '_Cadastro.csv' in c:
            crg = pd.read_csv('../datas/formatação/2017/'+d+'/'+c,encoding='iso-8859-1',delimiter='#')
            for v in crg.values:
                #Vinculo
                if str(v[27])+"_"+str(v[28]) not in VINCULOS_DISTINTOS:
                    VINCULOS_DISTINTOS.append(v[28])
                    
print(str(len(VINCULOS_DISTINTOS)))

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


KeyboardInterrupt: 

**Atenção:** Os valores possuem uma discrepância
* CARGOS: csv=2348;dw=2348.
* FUNÇÕES: csv=52; dw=50.
* VINCULOS: csv=;dw=.

In [2]:
SERVIDORES = []

#VERIFICANDOS OS SERVIDORES de 2016 e 2017
for d in os.listdir('../datas/2016/'):
    for c in os.listdir('../datas/2016/'+d):
        if '_Cadastro' in c:
            crg = pd.read_csv('../datas/2016/'+d+'/'+c,encoding='iso-8859-1',delimiter='\t')            
            for v in crg.values:
                #ID servidor portal
                if v[0] not in SERVIDORES:
                    SERVIDORES.append(v[0])

                    
for d in os.listdir('../datas/formatação/2017/'):
    for c in os.listdir('../datas/formatação/2017/'+d):
        if '_Cadastro.csv' in c:
            crg = pd.read_csv('../datas/formatação/2017/'+d+'/'+c,encoding='iso-8859-1',delimiter='#')
            for v in crg.values:
                #ID servidor portal
                if v[0] not in SERVIDORES:
                    SERVIDORES.append(v[0])
                    
print(str(len(SERVIDORES)))

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


KeyboardInterrupt: 

In [ ]:
ORGAOS_DISTINTOS = []

#VERIFICANDOS OS ORGÃOS de 2016 e 2017
for d in os.listdir('../datas/2016/'):
    for c in os.listdir('../datas/2016/'+d):
        if '_Cadastro' in c:
            crg = pd.read_csv('../datas/2016/'+d+'/'+c,encoding='iso-8859-1',delimiter='\t')            
            for v in crg.values:
                #ORGÃO DISTINTOS
                if v[15] not in ORGAOS_DISTINTOS: #COD_UORG_LOTACAO
                    ORGAOS_DISTINTOS.append(v[15])
                if v[17] not in ORGAOS_DISTINTOS: #COD_ORG_LOTACAO
                    ORGAOS_DISTINTOS.append(v[17])
                if v[19] not in ORGAOS_DISTINTOS: #COD_ORGSUP_LOTACAO
                    ORGAOS_DISTINTOS.append(v[19])
                if v[21] not in ORGAOS_DISTINTOS: #COD_UORG_EXERCICIO
                    ORGAOS_DISTINTOS.append(v[21])
                if v[23] not in ORGAOS_DISTINTOS: #COD_ORG_EXERCICIO
                    ORGAOS_DISTINTOS.append(v[23])
                if v[25] not in ORGAOS_DISTINTOS: #COD_ORGSUP_EXERCICIO
                    ORGAOS_DISTINTOS.append(v[25])

                    
for d in os.listdir('../datas/formatação/2017/'):
    for c in os.listdir('../datas/formatação/2017/'+d):
        if '_Cadastro.csv' in c:
            crg = pd.read_csv('../datas/formatação/2017/'+d+'/'+c,encoding='iso-8859-1',delimiter='#')
            for v in crg.values:
                #ORGÃO DISTINTOS
                if v[15] not in ORGAOS_DISTINTOS: #COD_UORG_LOTACAO
                    ORGAOS_DISTINTOS.append(v[15])
                if v[17] not in ORGAOS_DISTINTOS: #COD_ORG_LOTACAO
                    ORGAOS_DISTINTOS.append(v[17])
                if v[19] not in ORGAOS_DISTINTOS: #COD_ORGSUP_LOTACAO
                    ORGAOS_DISTINTOS.append(v[19])
                if v[21] not in ORGAOS_DISTINTOS: #COD_UORG_EXERCICIO
                    ORGAOS_DISTINTOS.append(v[21])
                if v[23] not in ORGAOS_DISTINTOS: #COD_ORG_EXERCICIO
                    ORGAOS_DISTINTOS.append(v[23])
                if v[25] not in ORGAOS_DISTINTOS: #COD_ORGSUP_EXERCICIO
                    ORGAOS_DISTINTOS.append(v[25])
                    
print(str(len(ORGAOS_DISTINTOS)))

/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/alysson.sousa/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,12,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


**Observação:** **Ainda não realizei a verificação no Pandas**, mas com base nas consultas do banco, pude perceber que nas tabelas da hierarquia de órgãos estam inconsistentes, pois as quantidades não correspondem a tabela *orgao* (que possui todos os órgãos, órgãos superiores e unidades gestoras).
* *orgao = 79138*
* *somatório das tabelas da hierarquia = 79868*